//Phase_1: Snowflake Environment
//Task_1: Create Warehouse
CREATE WAREHOUSE IF NOT EXISTS RETAIL_WH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

SHOW WAREHOUSES LIKE 'RETAIL_WH';

//Task_2: Create Database
CREATE DATABASE IF NOT EXISTS RETAIL_DB;

SHOW DATABASES LIKE 'RETAIL_DB';

//Task_3: Create Schema
CREATE SCHEMA IF NOT EXISTS RETAIL_DB.SALES_SCHEMA;

SHOW SCHEMAS IN DATABASE RETAIL_DB;
SHOW STAGES IN SCHEMA RETAIL_DB.SALES_SCHEMA;
LIST @RETAIL_DB.SALES_SCHEMA.RETAIL_STAGE;
//Task_4: Select warehouse, Database and Schema 
USE WAREHOUSE RETAIL_WH;

USE DATABASE RETAIL_DB;

USE SCHEMA SALES_SCHEMA;

//Task_5: Create CSV File Format 
CREATE OR REPLACE FILE FORMAT CSV_FORMAT
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    EMPTY_FIELD_AS_NULL = TRUE;

//Task_6: Create Internal Storage
CREATE OR REPLACE STAGE RETAIL_STAGE
    FILE_FORMAT = CSV_FORMAT;
SHOW STAGES;

LIST @RETAIL_STAGE;

//Phase_2: Data Loading 
//Task_7: Create Customers Table
CREATE OR REPLACE TABLE CUSTOMERS (
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(100),
    MEMBERSHIP VARCHAR(50)
);

//Task_8: Create Products Table
CREATE OR REPLACE TABLE PRODUCTS (
    PRODUCT_ID NUMBER,
    PRODUCT_NAME VARCHAR(100),
    CATEGORY VARCHAR(100),
    PRICE NUMBER(12,2)
);

//Task_9: Create Branches Table
CREATE OR REPLACE TABLE BRANCHES (
    BRANCH_ID NUMBER,
    BRANCH_NAME VARCHAR(100),
    CITY VARCHAR(100)
);

//Task_10: Create Sales Table
CREATE OR REPLACE TABLE SALES (
    SALE_ID NUMBER,
    CUSTOMER_ID NUMBER,
    PRODUCT_ID NUMBER,
    BRANCH_ID NUMBER,
    QUANTITY NUMBER,
    SALE_DATE DATE,
    TOTAL_AMOUNT NUMBER(12,2)
);

//Task_11: Verify Tables
SHOW TABLES;

//Task_12: Upload CSV Files
LIST @RETAIL_STAGE;

//Task_13: Load Customers
COPY INTO CUSTOMERS
FROM @RETAIL_STAGE/customers.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT)
ON_ERROR = 'CONTINUE';

//Task_14: Load Products
COPY INTO PRODUCTS
FROM @RETAIL_STAGE/products.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT)
ON_ERROR = 'CONTINUE';

//Task_15: Load Branches
COPY INTO BRANCHES
FROM @RETAIL_STAGE/branches.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT)
ON_ERROR = 'CONTINUE';

//Task_16: Load Sales
COPY INTO SALES
FROM @RETAIL_STAGE/sales.csv
FILE_FORMAT = (
    FORMAT_NAME = CSV_FORMAT
    DATE_FORMAT = 'DD-MM-YYYY'
)
ON_ERROR = 'ABORT_STATEMENT';
SELECT * FROM SALES;
//Task_17: Verify imported data
SELECT 'CUSTOMERS' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT
FROM CUSTOMERS

UNION ALL

SELECT 'PRODUCTS', COUNT(*)
FROM PRODUCTS

UNION ALL

SELECT 'BRANCHES', COUNT(*)
FROM BRANCHES

UNION ALL

SELECT 'SALES', COUNT(*)
FROM SALES;

//Phase_3: SQL Analytics
//Task_18: Display all Customers
SELECT *
FROM CUSTOMERS
ORDER BY CUSTOMER_ID;

//Task_19: Display all Products
SELECT *
FROM PRODUCTS
ORDER BY PRODUCT_ID;

//Task_20: Display all Branches
SELECT *
FROM BRANCHES
ORDER BY BRANCH_ID;

//Task_21: ALl sales transaction
SELECT *
FROM SALES
ORDER BY SALE_ID;

//Task_22: Calculate total business revenue
SELECT
    SUM(TOTAL_AMOUNT) AS TOTAL_BUSINESS_REVENUE
FROM SALES;

//Task_23: Customer wise sales
SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    C.CITY,
    C.MEMBERSHIP,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_SALES
FROM CUSTOMERS C
JOIN SALES S
    ON C.CUSTOMER_ID = S.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    C.CITY,
    C.MEMBERSHIP
ORDER BY TOTAL_SALES DESC;

//Task_24: Branch wise sales
SELECT
    B.BRANCH_ID,
    B.BRANCH_NAME,
    B.CITY,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_SALES
FROM BRANCHES B
JOIN SALES S
    ON B.BRANCH_ID = S.BRANCH_ID
GROUP BY
    B.BRANCH_ID,
    B.BRANCH_NAME,
    B.CITY
ORDER BY TOTAL_SALES DESC;

//Task_25: Product wise sales
SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    SUM(S.QUANTITY) AS TOTAL_QUANTITY_SOLD,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM PRODUCTS P
JOIN SALES S
    ON P.PRODUCT_ID = S.PRODUCT_ID
GROUP BY
    P.PRODUCT_ID,
    P.PRODUCT_NAME
ORDER BY TOTAL_REVENUE DESC;

//Task_26: Category wise sales
SELECT
    P.CATEGORY,
    SUM(S.QUANTITY) AS TOTAL_QUANTITY_SOLD,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM PRODUCTS P
JOIN SALES S
    ON P.PRODUCT_ID = S.PRODUCT_ID
GROUP BY P.CATEGORY
ORDER BY TOTAL_REVENUE DESC;

//Task_27: Highest Revenue Branch
SELECT
    B.BRANCH_ID,
    B.BRANCH_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM BRANCHES B
JOIN SALES S
    ON B.BRANCH_ID = S.BRANCH_ID
GROUP BY
    B.BRANCH_ID,
    B.BRANCH_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 1;

//Task_28: Highest Spending Customer
SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_SPENDING
FROM CUSTOMERS C
JOIN SALES S
    ON C.CUSTOMER_ID = S.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME
ORDER BY TOTAL_SPENDING DESC
LIMIT 1;

//Task_29: Top 3 Products by Revenue
SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.CATEGORY,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM PRODUCTS P
JOIN SALES S
    ON P.PRODUCT_ID = S.PRODUCT_ID
GROUP BY
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.CATEGORY
ORDER BY TOTAL_REVENUE DESC
LIMIT 3;

//Task_30: Top 3 Customers by Revenue
SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_SPENDING
FROM CUSTOMERS C
JOIN SALES S
    ON C.CUSTOMER_ID = S.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME
ORDER BY TOTAL_SPENDING DESC
LIMIT 3;

//Phase_4
//Task_31: Rank Customers Based on Total Spending
SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_SPENDING,
    RANK() OVER (
        ORDER BY SUM(S.TOTAL_AMOUNT) DESC
    ) AS CUSTOMER_RANK
FROM CUSTOMERS C
JOIN SALES S
    ON C.CUSTOMER_ID = S.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME
ORDER BY CUSTOMER_RANK;

//Task_32: Rank Branches Based on Total Sales
SELECT
    B.BRANCH_ID,
    B.BRANCH_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_SALES,
    RANK() OVER (
        ORDER BY SUM(S.TOTAL_AMOUNT) DESC
    ) AS BRANCH_RANK
FROM BRANCHES B
JOIN SALES S
    ON B.BRANCH_ID = S.BRANCH_ID
GROUP BY
    B.BRANCH_ID,
    B.BRANCH_NAME
ORDER BY BRANCH_RANK;

//Task_33: Top-Selling Product in Each Category
WITH PRODUCT_SALES AS (
    SELECT
        P.PRODUCT_ID,
        P.PRODUCT_NAME,
        P.CATEGORY,
        SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE
    FROM PRODUCTS P
    JOIN SALES S
        ON P.PRODUCT_ID = S.PRODUCT_ID
    GROUP BY
        P.PRODUCT_ID,
        P.PRODUCT_NAME,
        P.CATEGORY
),

RANKED_PRODUCTS AS (
    SELECT
        PRODUCT_ID,
        PRODUCT_NAME,
        CATEGORY,
        TOTAL_REVENUE,
        ROW_NUMBER() OVER (
            PARTITION BY CATEGORY
            ORDER BY TOTAL_REVENUE DESC
        ) AS RN
    FROM PRODUCT_SALES
)

SELECT
    PRODUCT_ID,
    PRODUCT_NAME,
    CATEGORY,
    TOTAL_REVENUE
FROM RANKED_PRODUCTS
WHERE RN = 1
ORDER BY CATEGORY;

//Task_34: Calculate Cumulative Sales
SELECT
    SALE_ID,
    SALE_DATE,
    TOTAL_AMOUNT,
    SUM(TOTAL_AMOUNT) OVER (
        ORDER BY SALE_DATE, SALE_ID
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS CUMULATIVE_SALES
FROM SALES
ORDER BY SALE_DATE, SALE_ID;

//Task_35: Calculate Average Sale Amount Using AVG() OVER()
SELECT
    SALE_ID,
    SALE_DATE,
    TOTAL_AMOUNT,
    AVG(TOTAL_AMOUNT) OVER () AS AVERAGE_SALE_AMOUNT
FROM SALES
ORDER BY SALE_ID;

//Phase 5
//Task_36: Customer-wise Revenue Using CTE
WITH CUSTOMER_REVENUE AS (
    SELECT
        C.CUSTOMER_ID,
        C.CUSTOMER_NAME,
        SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE
    FROM CUSTOMERS C
    JOIN SALES S
        ON C.CUSTOMER_ID = S.CUSTOMER_ID
    GROUP BY
        C.CUSTOMER_ID,
        C.CUSTOMER_NAME
)

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    TOTAL_REVENUE
FROM CUSTOMER_REVENUE
ORDER BY TOTAL_REVENUE DESC;

//Task_37: Customers Spending Greater Than Average
WITH CUSTOMER_SPENDING AS (
    SELECT
        C.CUSTOMER_ID,
        C.CUSTOMER_NAME,
        SUM(S.TOTAL_AMOUNT) AS TOTAL_SPENDING
    FROM CUSTOMERS C
    JOIN SALES S
        ON C.CUSTOMER_ID = S.CUSTOMER_ID
    GROUP BY
        C.CUSTOMER_ID,
        C.CUSTOMER_NAME
),

AVERAGE_SPENDING AS (
    SELECT
        AVG(TOTAL_SPENDING) AS AVG_SPENDING
    FROM CUSTOMER_SPENDING
)

SELECT
    CS.CUSTOMER_ID,
    CS.CUSTOMER_NAME,
    CS.TOTAL_SPENDING
FROM CUSTOMER_SPENDING CS
CROSS JOIN AVERAGE_SPENDING A
WHERE CS.TOTAL_SPENDING > A.AVG_SPENDING
ORDER BY CS.TOTAL_SPENDING DESC;

//Phase 6
//Task_38: Create SALES_REPORT View
CREATE OR REPLACE VIEW SALES_REPORT AS
SELECT
    S.SALE_ID,
    S.SALE_DATE,

    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    C.MEMBERSHIP,

    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.CATEGORY,
    P.PRICE,

    B.BRANCH_ID,
    B.BRANCH_NAME,
    B.CITY AS BRANCH_CITY,

    S.QUANTITY,
    S.TOTAL_AMOUNT

FROM SALES S

JOIN CUSTOMERS C
    ON S.CUSTOMER_ID = C.CUSTOMER_ID

JOIN PRODUCTS P
    ON S.PRODUCT_ID = P.PRODUCT_ID

JOIN BRANCHES B
    ON S.BRANCH_ID = B.BRANCH_ID;

//Task_39: Query SALES_REPORT
SELECT *
FROM SALES_REPORT
ORDER BY SALE_ID;

//Task_40: Create Materialized View TOP_CUSTOMERS
CREATE OR REPLACE MATERIALIZED VIEW TOP_CUSTOMERS AS
SELECT
    CUSTOMER_ID,
    SUM(TOTAL_AMOUNT) AS TOTAL_SPENDING
FROM SALES
GROUP BY CUSTOMER_ID;

//Task_41: Query Materialized View
SELECT
    TC.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    TC.TOTAL_SPENDING
FROM TOP_CUSTOMERS TC
JOIN CUSTOMERS C
    ON TC.CUSTOMER_ID = C.CUSTOMER_ID
ORDER BY TC.TOTAL_SPENDING DESC;

