-- TASK 1: CREATE SNOWFLAKE ENVIRONMENT

CREATE WAREHOUSE IF NOT EXISTS HEALTHCARE_WH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

USE WAREHOUSE HEALTHCARE_WH;

CREATE DATABASE IF NOT EXISTS HEALTHCARE_DB;
USE DATABASE HEALTHCARE_DB;

CREATE SCHEMA IF NOT EXISTS HEALTHCARE_SCHEMA;
USE SCHEMA HEALTHCARE_SCHEMA;


CREATE OR REPLACE TABLE DIM_PATIENT (
    PATIENT_KEY INTEGER AUTOINCREMENT,
    PATIENT_ID VARCHAR(20),
    PATIENT_NAME VARCHAR(100),
    GENDER VARCHAR(20),
    CITY VARCHAR(100),
    STATE VARCHAR(100)
);

CREATE OR REPLACE TABLE DIM_DOCTOR (
    DOCTOR_KEY INTEGER AUTOINCREMENT,
    DOCTOR_ID VARCHAR(20),
    DOCTOR_NAME VARCHAR(100),
    SPECIALIZATION VARCHAR(100)
);

CREATE OR REPLACE TABLE DIM_HOSPITAL (
    HOSPITAL_KEY INTEGER AUTOINCREMENT,
    HOSPITAL_ID VARCHAR(20),
    HOSPITAL_NAME VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    REGION VARCHAR(50)
);

CREATE OR REPLACE TABLE DIM_DEPARTMENT (
    DEPARTMENT_KEY INTEGER AUTOINCREMENT,
    DEPARTMENT_ID VARCHAR(20),
    DEPARTMENT_NAME VARCHAR(100)
);

CREATE OR REPLACE TABLE DIM_TREATMENT (
    TREATMENT_KEY INTEGER AUTOINCREMENT,
    TREATMENT_ID VARCHAR(20),
    TREATMENT_NAME VARCHAR(100),
    TREATMENT_CATEGORY VARCHAR(100)
);

CREATE OR REPLACE TABLE DIM_DATE (
    DATE_KEY INTEGER,
    FULL_DATE DATE,
    DAY INTEGER,
    DAY_NAME VARCHAR(20),
    WEEK_NO INTEGER,
    MONTH INTEGER,
    MONTH_NAME VARCHAR(20),
    QUARTER VARCHAR(5),
    YEAR INTEGER
);


CREATE TABLE IF NOT EXISTS PATIENTS (
    PATIENT_ID VARCHAR(20),
    PATIENT_NAME VARCHAR(100),
    GENDER VARCHAR(20),
    CITY VARCHAR(100),
    STATE VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS DOCTORS (
    DOCTOR_ID VARCHAR(20),
    DOCTOR_NAME VARCHAR(100),
    SPECIALIZATION VARCHAR(100)
);

COPY INTO DOCTORS
FROM @HEALTHCARE_STAGE/doctors.csv
FILE_FORMAT = (
    FORMAT_NAME = 'CSV_FORMAT'
    SKIP_HEADER = 1
);

CREATE TABLE IF NOT EXISTS HOSPITALS (
    HOSPITAL_ID VARCHAR(20),
    HOSPITAL_NAME VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    REGION VARCHAR(50)
);
COPY INTO HOSPITALS
FROM @HEALTHCARE_STAGE/hospitals.csv
FILE_FORMAT = (
    FORMAT_NAME = 'CSV_FORMAT'
    SKIP_HEADER = 1
);

CREATE TABLE IF NOT EXISTS DEPARTMENTS (
    DEPARTMENT_ID VARCHAR(20),
    DEPARTMENT_NAME VARCHAR(100)
);
COPY INTO DEPARTMENTS
FROM @HEALTHCARE_STAGE/departments.csv
FILE_FORMAT = (
    FORMAT_NAME = 'CSV_FORMAT'
    SKIP_HEADER = 1
);

CREATE TABLE IF NOT EXISTS TREATMENTS (
    TREATMENT_ID VARCHAR(20),
    TREATMENT_NAME VARCHAR(100),
    TREATMENT_CATEGORY VARCHAR(100)
);

COPY INTO TREATMENTS
FROM @HEALTHCARE_STAGE/treatments.csv
FILE_FORMAT = (
    FORMAT_NAME = 'CSV_FORMAT'
    SKIP_HEADER = 1
);

CREATE TABLE IF NOT EXISTS ADMISSIONS (
    ADMISSION_ID VARCHAR(20),
    PATIENT_ID VARCHAR(20),
    DOCTOR_ID VARCHAR(20),
    HOSPITAL_ID VARCHAR(20),
    DEPARTMENT_ID VARCHAR(20),
    ADMISSION_DATE DATE,
    DISCHARGE_DATE DATE
);

TRUNCATE TABLE ADMISSIONS;

COPY INTO ADMISSIONS
FROM @HEALTHCARE_STAGE/admissions.csv
FILE_FORMAT = (
    FORMAT_NAME = 'CSV_FORMAT'
    SKIP_HEADER = 3
    DATE_FORMAT = 'DD-MM-YYYY'
);

CREATE OR REPLACE TABLE BILLING (
    BILLING_ID VARCHAR(20),
    PATIENT_ID VARCHAR(20),
    DOCTOR_ID VARCHAR(20),
    HOSPITAL_ID VARCHAR(20),
    DEPARTMENT_ID VARCHAR(20),
    TREATMENT_ID VARCHAR(20),
    BILLING_DATE DATE,
    QUANTITY INTEGER,
    TREATMENT_AMOUNT NUMBER(10,2),
    DISCOUNT NUMBER(10,2),
    NET_AMOUNT NUMBER(10,2)
);

TRUNCATE TABLE BILLING;

COPY INTO BILLING
FROM @HEALTHCARE_STAGE/billing_corrected.csv
FILE_FORMAT = (
    FORMAT_NAME = 'CSV_FORMAT'
    DATE_FORMAT = 'DD-MM-YYYY'
);


INSERT INTO DIM_PATIENT
    (PATIENT_ID, PATIENT_NAME, GENDER, CITY, STATE)
SELECT
    PATIENT_ID, PATIENT_NAME, GENDER, CITY, STATE
FROM PATIENTS;

INSERT INTO DIM_DOCTOR
    (DOCTOR_ID, DOCTOR_NAME, SPECIALIZATION)
SELECT
    DOCTOR_ID, DOCTOR_NAME, SPECIALIZATION
FROM DOCTORS
WHERE DOCTOR_ID IS NOT NULL
  AND DOCTOR_ID <> '-----------'
  AND DOCTOR_ID <> 'doctor_id';

INSERT INTO DIM_HOSPITAL
    (HOSPITAL_ID, HOSPITAL_NAME, CITY, STATE, REGION)
SELECT
    HOSPITAL_ID, HOSPITAL_NAME, CITY, STATE, REGION
FROM HOSPITALS
WHERE HOSPITAL_ID IS NOT NULL
  AND HOSPITAL_ID <> '-----------'
  AND HOSPITAL_ID <> 'hospital_id';


INSERT INTO DIM_DEPARTMENT
    (DEPARTMENT_ID, DEPARTMENT_NAME)
SELECT
    DEPARTMENT_ID, DEPARTMENT_NAME
FROM DEPARTMENTS
WHERE DEPARTMENT_ID IS NOT NULL
  AND DEPARTMENT_ID <> '-----------'
  AND DEPARTMENT_ID <> 'department_id';

INSERT INTO DIM_TREATMENT 
    (TREATMENT_ID, TREATMENT_NAME, TREATMENT_CATEGORY)
SELECT 
    TREATMENT_ID, TREATMENT_NAME, TREATMENT_CATEGORY
FROM TREATMENTS
WHERE TREATMENT_ID IS NOT NULL
  AND TREATMENT_ID <> '-----------'
  AND TREATMENT_ID <> 'treatment_id';

INSERT INTO DIM_DATE
SELECT
    TO_NUMBER(TO_CHAR(DATE_VALUE, 'YYYYMMDD')) AS DATE_KEY,
    DATE_VALUE AS FULL_DATE,
    DAY(DATE_VALUE) AS DAY,
    DAYNAME(DATE_VALUE) AS DAY_NAME,
    WEEK(DATE_VALUE) AS WEEK_NO,
    MONTH(DATE_VALUE) AS MONTH,
    MONTHNAME(DATE_VALUE) AS MONTH_NAME,
    'Q' || QUARTER(DATE_VALUE) AS QUARTER,
    YEAR(DATE_VALUE) AS YEAR
FROM (
    SELECT DATEADD(DAY, SEQ4(), '2026-01-01'::DATE) AS DATE_VALUE
    FROM TABLE(GENERATOR(ROWCOUNT => 90))
);

CREATE OR REPLACE TABLE FACT_ADMISSION (
    ADMISSION_KEY INTEGER AUTOINCREMENT,
    PATIENT_KEY INTEGER,
    DOCTOR_KEY INTEGER,
    HOSPITAL_KEY INTEGER,
    DEPARTMENT_KEY INTEGER,
    DATE_KEY INTEGER,
    ADMISSION_COUNT INTEGER,
    LENGTH_OF_STAY INTEGER
);

CREATE OR REPLACE TABLE FACT_BILLING (
    BILLING_KEY INTEGER AUTOINCREMENT,
    PATIENT_KEY INTEGER,
    DOCTOR_KEY INTEGER,
    HOSPITAL_KEY INTEGER,
    DEPARTMENT_KEY INTEGER,
    TREATMENT_KEY INTEGER,
    DATE_KEY INTEGER,
    QUANTITY INTEGER,
    TREATMENT_AMOUNT NUMBER(10,2),
    DISCOUNT NUMBER(10,2),
    NET_AMOUNT NUMBER(10,2)
);
INSERT INTO FACT_ADMISSION (
    PATIENT_KEY,
    DOCTOR_KEY,
    HOSPITAL_KEY,
    DEPARTMENT_KEY,
    DATE_KEY,
    ADMISSION_COUNT,
    LENGTH_OF_STAY
)
SELECT
    P.PATIENT_KEY,
    D.DOCTOR_KEY,
    H.HOSPITAL_KEY,
    DP.DEPARTMENT_KEY,
    TO_NUMBER(TO_CHAR(A.ADMISSION_DATE, 'YYYYMMDD')) AS DATE_KEY,
    1 AS ADMISSION_COUNT,
    DATEDIFF(DAY, A.ADMISSION_DATE, A.DISCHARGE_DATE) AS LENGTH_OF_STAY
FROM ADMISSIONS A
JOIN DIM_PATIENT P ON A.PATIENT_ID = P.PATIENT_ID
JOIN DIM_DOCTOR D ON A.DOCTOR_ID = D.DOCTOR_ID
JOIN DIM_HOSPITAL H ON A.HOSPITAL_ID = H.HOSPITAL_ID
JOIN DIM_DEPARTMENT DP ON A.DEPARTMENT_ID = DP.DEPARTMENT_ID;

INSERT INTO FACT_BILLING (
    PATIENT_KEY,
    DOCTOR_KEY,
    HOSPITAL_KEY,
    DEPARTMENT_KEY,
    TREATMENT_KEY,
    DATE_KEY,
    QUANTITY,
    TREATMENT_AMOUNT,
    DISCOUNT,
    NET_AMOUNT
)
SELECT
    P.PATIENT_KEY,
    D.DOCTOR_KEY,
    H.HOSPITAL_KEY,
    DP.DEPARTMENT_KEY,
    DT.TREATMENT_KEY,
    TO_NUMBER(TO_CHAR(B.BILLING_DATE, 'YYYYMMDD')) AS DATE_KEY,
    B.QUANTITY,
    B.TREATMENT_AMOUNT,
    B.DISCOUNT,
    B.NET_AMOUNT
FROM BILLING B
JOIN DIM_PATIENT P ON B.PATIENT_ID = P.PATIENT_ID
JOIN DIM_DOCTOR D ON B.DOCTOR_ID = D.DOCTOR_ID
JOIN DIM_HOSPITAL H ON B.HOSPITAL_ID = H.HOSPITAL_ID
JOIN DIM_DEPARTMENT DP ON B.DEPARTMENT_ID = DP.DEPARTMENT_ID
JOIN DIM_TREATMENT DT ON B.TREATMENT_ID = DT.TREATMENT_ID;

SELECT
    H.HOSPITAL_NAME,
    SUM(F.ADMISSION_COUNT) AS TOTAL_ADMISSIONS
FROM FACT_ADMISSION F
JOIN DIM_HOSPITAL H ON F.HOSPITAL_KEY = H.HOSPITAL_KEY
GROUP BY H.HOSPITAL_NAME
ORDER BY TOTAL_ADMISSIONS DESC;

SELECT
    H.HOSPITAL_NAME,
    SUM(F.NET_AMOUNT) AS TOTAL_REVENUE
FROM FACT_BILLING F
JOIN DIM_HOSPITAL H ON F.HOSPITAL_KEY = H.HOSPITAL_KEY
GROUP BY H.HOSPITAL_NAME
ORDER BY TOTAL_REVENUE DESC;

SELECT
    TO_CHAR(D.FULL_DATE, 'YYYY-MM') AS MONTH,
    SUM(F.NET_AMOUNT) AS TOTAL_REVENUE
FROM FACT_BILLING F
JOIN DIM_DATE D ON F.DATE_KEY = D.DATE_KEY
GROUP BY TO_CHAR(D.FULL_DATE, 'YYYY-MM')
ORDER BY MONTH;

SELECT
    D.DOCTOR_NAME,
    SUM(F.NET_AMOUNT) AS TOTAL_REVENUE
FROM FACT_BILLING F
JOIN DIM_DOCTOR D ON F.DOCTOR_KEY = D.DOCTOR_KEY
GROUP BY D.DOCTOR_NAME
ORDER BY TOTAL_REVENUE DESC;


SELECT
    H.HOSPITAL_NAME,
    COALESCE(A.TOTAL_ADMISSIONS, 0) AS TOTAL_ADMISSIONS,
    COALESCE(B.TOTAL_REVENUE, 0) AS TOTAL_REVENUE
FROM DIM_HOSPITAL H
LEFT JOIN (
    SELECT HOSPITAL_KEY, SUM(ADMISSION_COUNT) AS TOTAL_ADMISSIONS
    FROM FACT_ADMISSION
    GROUP BY HOSPITAL_KEY
) A ON H.HOSPITAL_KEY = A.HOSPITAL_KEY
LEFT JOIN (
    SELECT HOSPITAL_KEY, SUM(NET_AMOUNT) AS TOTAL_REVENUE
    FROM FACT_BILLING
    GROUP BY HOSPITAL_KEY
) B ON H.HOSPITAL_KEY = B.HOSPITAL_KEY
ORDER BY TOTAL_ADMISSIONS DESC;









