CREATE WAREHOUSE IF NOT EXISTS RETAIL_WH
WITH 
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

USE WAREHOUSE RETAIL_WH;

CREATE DATABASE RETAIL_DB;
USE DATABASE RETAIL_DB;

CREATE SCHEMA RETAIL_SCHEMA;
USE SCHEMA RETAIL_SCHEMA;

SELECT 
    CURRENT_WAREHOUSE(),
    CURRENT_DATABASE(),
    CURRENT_SCHEMA();

CREATE FILE FORMAT RETAIL_CSV_FORMAT
TYPE = 'CSV'
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"' 
TRIM_SPACE = TRUE
NULL_IF = ('NULL', 'null', '');

SHOW FILE FORMATS;

CREATE STAGE RETAIL_STAGE
FILE_FORMAT = RETAIL_CSV_FORMAT;

SHOW STAGES;

LIST @RETAIL_STAGE;

CREATE TABLE DIM_CUSTOMER (
    CUSTOMER_ID NUMBER PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    MEMBERSHIP VARCHAR(20)
);
DESC TABLE RETAIL_DB.RETAIL_SCHEMA.DIM_CUSTOMER;

CREATE TABLE DIM_PRODUCT (
    PRODUCT_ID NUMBER PRIMARY KEY,
    PRODUCT_NAME VARCHAR(100),
    CATEGORY VARCHAR(100),
    BRAND VARCHAR(100),
    PRICE NUMBER(12,3)
);
DESC TABLE RETAIL_DB.RETAIL_SCHEMA.DIM_PRODUCT;

CREATE TABLE DIM_BRANCH (
    BRANCH_ID NUMBER PRIMARY KEY,
    BRANCH_NAME VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    REGION VARCHAR(50),
    MANAGER_NAME VARCHAR(100)
);

DESC TABLE RETAIL_DB.RETAIL_SCHEMA.DIM_BRANCH;

CREATE TABLE DIM_DATE (
    DATE_ID NUMBER PRIMARY KEY,
    DATE_VALUE DATE,
    DAY NUMBER,
    DAY_NAME VARCHAR(20),
    WEEK_NO NUMBER,
    MONTH VARCHAR(20),
    QUARTER VARCHAR(10),
    YEAR NUMBER,
    IS_WEEKEND BOOLEAN
);

DESC TABLE RETAIL_DB.RETAIL_SCHEMA.DIM_DATE;

CREATE TABLE FACT_SALES (
    SALE_ID NUMBER PRIMARY KEY,
    CUSTOMER_ID NUMBER,
    PRODUCT_ID NUMBER,
    BRANCH_ID NUMBER,
    DATE_ID NUMBER,
    QUANTITY NUMBER,
    TOTAL_AMOUNT NUMBER(14,2),

    FOREIGN KEY (CUSTOMER_ID)
        REFERENCES DIM_CUSTOMER(CUSTOMER_ID),

    FOREIGN KEY (PRODUCT_ID)
        REFERENCES DIM_PRODUCT(PRODUCT_ID),

    FOREIGN KEY (BRANCH_ID)
        REFERENCES DIM_BRANCH(BRANCH_ID),

    FOREIGN KEY (DATE_ID)
        REFERENCES DIM_DATE(DATE_ID)
);
DESC TABLE RETAIL_DB.RETAIL_SCHEMA.FACT_SALES;
SHOW TABLES IN SCHEMA RETAIL_DB.RETAIL_SCHEMA;


COPY INTO DIM_CUSTOMER
FROM @RETAIL_STAGE/customers.csv
FILE_FORMAT = (FORMAT_NAME = RETAIL_CSV_FORMAT)
ON_ERROR = 'ABORT_STATEMENT';
SELECT COUNT(*) FROM DIM_CUSTOMER;

COPY INTO DIM_PRODUCT
FROM @RETAIL_STAGE/products.csv
FILE_FORMAT = (FORMAT_NAME = RETAIL_CSV_FORMAT)
ON_ERROR = 'ABORT_STATEMENT';
SELECT COUNT(*) FROM DIM_PRODUCT;

COPY INTO DIM_BRANCH
FROM @RETAIL_STAGE/branches.csv
FILE_FORMAT = (FORMAT_NAME = RETAIL_CSV_FORMAT)
ON_ERROR = 'ABORT_STATEMENT';
SELECT COUNT(*) FROM DIM_BRANCH;

COPY INTO DIM_DATE
FROM @RETAIL_STAGE/calendar.csv
FILE_FORMAT = (FORMAT_NAME = RETAIL_CSV_FORMAT)
ON_ERROR = 'ABORT_STATEMENT';
ALTER FILE FORMAT RETAIL_CSV_FORMAT
SET DATE_FORMAT = 'DD-MM-YYYY';
SELECT COUNT(*) FROM DIM_DATE;

COPY INTO FACT_SALES
FROM @RETAIL_STAGE/sales.csv
FILE_FORMAT = (FORMAT_NAME = RETAIL_CSV_FORMAT)
ON_ERROR = 'ABORT_STATEMENT';

SELECT 'DIM_CUSTOMER' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM DIM_CUSTOMER
UNION ALL
SELECT 'DIM_PRODUCT', COUNT(*) FROM DIM_PRODUCT
UNION ALL
SELECT 'DIM_BRANCH', COUNT(*) FROM DIM_BRANCH
UNION ALL
SELECT 'DIM_DATE', COUNT(*) FROM DIM_DATE
UNION ALL
SELECT 'FACT_SALES', COUNT(*) FROM FACT_SALES;

DESCRIBE TABLE DIM_CUSTOMER;
DESCRIBE TABLE DIM_PRODUCT;
DESCRIBE TABLE DIM_BRANCH;
DESCRIBE TABLE DIM_DATE;

CREATE TABLE DIM_STATE (
    STATE_ID NUMBER PRIMARY KEY,
    STATE_NAME VARCHAR(100),
    REGION_ID NUMBER
);

CREATE TABLE DIM_CITY (
    CITY_ID NUMBER PRIMARY KEY,
    CITY_NAME VARCHAR(100),
    STATE_ID NUMBER,
    FOREIGN KEY (STATE_ID) REFERENCES DIM_STATE(STATE_ID)
);

CREATE TABLE DIM_REGION (
    REGION_ID NUMBER PRIMARY KEY,
    REGION_NAME VARCHAR(50)
);

CREATE TABLE DIM_CATEGORY (
    CATEGORY_ID NUMBER PRIMARY KEY,
    CATEGORY_NAME VARCHAR(100)
);

CREATE TABLE DIM_BRAND (
    BRAND_ID NUMBER PRIMARY KEY,
    BRAND_NAME VARCHAR(100),
    CATEGORY_ID NUMBER,
    FOREIGN KEY (CATEGORY_ID) REFERENCES DIM_CATEGORY(CATEGORY_ID)
);

CREATE TABLE DIM_YEAR (
    YEAR_ID NUMBER PRIMARY KEY,
    YEAR_VALUE NUMBER
);

CREATE TABLE DIM_QUARTER (
    QUARTER_ID NUMBER PRIMARY KEY,
    QUARTER_NAME VARCHAR(10),
    YEAR_ID NUMBER,
    FOREIGN KEY (YEAR_ID) REFERENCES DIM_YEAR(YEAR_ID)
);

CREATE TABLE DIM_MONTH (
    MONTH_ID NUMBER PRIMARY KEY,
    MONTH_NAME VARCHAR(20),
    QUARTER_ID NUMBER,
    FOREIGN KEY (QUARTER_ID) REFERENCES DIM_QUARTER(QUARTER_ID)
);

INSERT INTO DIM_REGION (REGION_ID, REGION_NAME)
VALUES
(1, 'South'),
(2, 'West'),
(3, 'North'),
(4, 'East');

SELECT * FROM DIM_REGION
ORDER BY REGION_ID;

INSERT INTO DIM_STATE (STATE_ID, STATE_NAME, REGION_ID)
VALUES
(1, 'Telangana', 1),
(2, 'Karnataka', 1),
(3, 'Tamil Nadu', 1),
(4, 'Andhra Pradesh', 1),
(5, 'Maharashtra', 2),
(6, 'Gujarat', 2),
(7, 'Delhi', 3),
(8, 'Rajasthan', 3),
(9, 'Uttar Pradesh', 3),
(10, 'West Bengal', 4),
(11, 'Kerala', 1),
(12, 'Bihar', 3),
(13, 'Madhya Pradesh', 3),
(14, 'Chandigarh', 3);

SELECT * FROM DIM_STATE
ORDER BY STATE_ID;

INSERT INTO DIM_CITY (CITY_ID, CITY_NAME, STATE_ID)
VALUES
(1, 'Hyderabad', 1),
(2, 'Bangalore', 2),
(3, 'Chennai', 3),
(4, 'Ahmedabad', 6),
(5, 'Delhi', 7),
(6, 'Vijayawada', 4),
(7, 'Warangal', 1),
(8, 'Mumbai', 5),
(9, 'Jaipur', 8),
(10, 'Kochi', 11),
(11, 'Visakhapatnam', 4),
(12, 'Kolkata', 10),
(13, 'Lucknow', 9),
(14, 'Coimbatore', 3),
(15, 'Patna', 12),
(16, 'Bhopal', 13),
(17, 'Chandigarh', 14),
(18, 'Mysore', 2),
(19, 'Nagpur', 5),
(20, 'Thiruvananthapuram', 11);

SELECT * FROM DIM_CITY
ORDER BY CITY_ID;

INSERT INTO DIM_CATEGORY (CATEGORY_ID, CATEGORY_NAME)
VALUES
(1, 'Electronics'),
(2, 'Accessories'),
(3, 'Office Equipment'),
(4, 'Networking'),
(5, 'Storage'),
(6, 'Mobile Accessories');

SELECT * FROM DIM_CATEGORY
ORDER BY CATEGORY_ID;

INSERT INTO DIM_BRAND (BRAND_ID, BRAND_NAME, CATEGORY_ID)
VALUES
(1, 'Dell', 1),
(2, 'Samsung', 1),
(3, 'Apple', 1),
(4, 'LG', 1),
(5, 'Logitech', 2),
(6, 'HP', 2),
(7, 'Sony', 2),
(8, 'JBL', 2),
(9, 'Canon', 3),
(10, 'Epson', 3),
(11, 'TP-Link', 4),
(12, 'Cisco', 4),
(13, 'Seagate', 5),
(14, 'SanDisk', 5),
(15, 'Mi', 6),
(16, 'Anker', 6);

SELECT * FROM DIM_BRAND
ORDER BY BRAND_ID;

INSERT INTO DIM_YEAR (YEAR_ID, YEAR_VALUE)
VALUES
(1, 2026);
SELECT * FROM DIM_YEAR;

INSERT INTO DIM_QUARTER (QUARTER_ID, QUARTER_NAME, YEAR_ID)
VALUES
(1, 'Q3', 1);
SELECT * FROM DIM_QUARTER;

INSERT INTO DIM_MONTH (MONTH_ID, MONTH_NAME, QUARTER_ID)
VALUES
(1, 'July', 1);
SELECT * FROM DIM_MONTH;

SELECT 'DIM_REGION' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM DIM_REGION
UNION ALL
SELECT 'DIM_STATE', COUNT(*) FROM DIM_STATE
UNION ALL
SELECT 'DIM_CITY', COUNT(*) FROM DIM_CITY
UNION ALL
SELECT 'DIM_CATEGORY', COUNT(*) FROM DIM_CATEGORY
UNION ALL
SELECT 'DIM_BRAND', COUNT(*) FROM DIM_BRAND
UNION ALL
SELECT 'DIM_YEAR', COUNT(*) FROM DIM_YEAR
UNION ALL
SELECT 'DIM_QUARTER', COUNT(*) FROM DIM_QUARTER
UNION ALL
SELECT 'DIM_MONTH', COUNT(*) FROM DIM_MONTH;

ALTER TABLE DIM_CUSTOMER
ADD COLUMN CITY_ID NUMBER;

UPDATE DIM_CUSTOMER c
SET CITY_ID = d.CITY_ID
FROM DIM_CITY d
WHERE c.CITY = d.CITY_NAME;

SELECT CUSTOMER_ID, CUSTOMER_NAME, CITY, CITY_ID
FROM DIM_CUSTOMER
ORDER BY CUSTOMER_ID;

ALTER TABLE DIM_BRANCH
ADD COLUMN CITY_ID NUMBER;

UPDATE DIM_BRANCH b
SET CITY_ID = c.CITY_ID
FROM DIM_CITY c
WHERE b.CITY = c.CITY_NAME;

SELECT BRANCH_ID, BRANCH_NAME, CITY, CITY_ID
FROM DIM_BRANCH
ORDER BY BRANCH_ID;

ALTER TABLE DIM_PRODUCT
ADD COLUMN BRAND_ID NUMBER;

UPDATE DIM_PRODUCT p
SET BRAND_ID = b.BRAND_ID
FROM DIM_BRAND b
WHERE p.BRAND = b.BRAND_NAME;

SELECT PRODUCT_ID, PRODUCT_NAME, BRAND, BRAND_ID
FROM DIM_PRODUCT
ORDER BY PRODUCT_ID;

ALTER TABLE DIM_DATE
ADD COLUMN MONTH_ID NUMBER;

UPDATE DIM_DATE d
SET MONTH_ID = m.MONTH_ID
FROM DIM_MONTH m
WHERE d.MONTH = m.MONTH_NAME;

SELECT DATE_ID, DATE_VALUE, MONTH, MONTH_ID
FROM DIM_DATE
ORDER BY DATE_ID;


SELECT
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    c.CITY_ID,
    city.CITY_NAME,
    s.STATE_NAME,
    r.REGION_NAME
FROM DIM_CUSTOMER c
JOIN DIM_CITY city
    ON c.CITY_ID = city.CITY_ID
JOIN DIM_STATE s
    ON city.STATE_ID = s.STATE_ID
JOIN DIM_REGION r
    ON s.REGION_ID = r.REGION_ID
ORDER BY c.CUSTOMER_ID;

SELECT
    b.BRANCH_ID,
    b.BRANCH_NAME,
    b.CITY_ID,
    city.CITY_NAME,
    s.STATE_NAME,
    r.REGION_NAME
FROM DIM_BRANCH b
JOIN DIM_CITY city
    ON b.CITY_ID = city.CITY_ID
JOIN DIM_STATE s
    ON city.STATE_ID = s.STATE_ID
JOIN DIM_REGION r
    ON s.REGION_ID = r.REGION_ID
ORDER BY b.BRANCH_ID;

SELECT
    b.BRANCH_ID,
    b.BRANCH_NAME,
    b.CITY
FROM DIM_BRANCH b
LEFT JOIN DIM_CITY c
    ON b.CITY_ID = c.CITY_ID
WHERE c.CITY_ID IS NULL
ORDER BY b.BRANCH_ID;
UPDATE DIM_BRANCH
SET CITY_ID = (
    SELECT CITY_ID
    FROM DIM_CITY
    WHERE CITY_NAME = 'Lucknow'
)
WHERE BRANCH_ID = 10;

SELECT BRANCH_ID, BRANCH_NAME, CITY, CITY_ID
FROM DIM_BRANCH
WHERE BRANCH_ID = 10;


SELECT
    b.BRANCH_ID,
    b.BRANCH_NAME,
    b.CITY_ID,
    city.CITY_NAME,
    s.STATE_NAME,
    r.REGION_NAME
FROM DIM_BRANCH b
JOIN DIM_CITY city
    ON b.CITY_ID = city.CITY_ID
JOIN DIM_STATE s
    ON city.STATE_ID = s.STATE_ID
JOIN DIM_REGION r
    ON s.REGION_ID = r.REGION_ID
ORDER BY b.BRANCH_ID;

SELECT
    p.PRODUCT_ID,
    p.PRODUCT_NAME,
    p.BRAND_ID,
    b.BRAND_NAME,
    c.CATEGORY_NAME
FROM DIM_PRODUCT p
JOIN DIM_BRAND b
    ON p.BRAND_ID = b.BRAND_ID
JOIN DIM_CATEGORY c
    ON b.CATEGORY_ID = c.CATEGORY_ID
ORDER BY p.PRODUCT_ID;

SELECT
    d.DATE_ID,
    d.DATE_VALUE,
    d.MONTH_ID,
    m.MONTH_NAME,
    q.QUARTER_NAME,
    y.YEAR_VALUE
FROM DIM_DATE d
JOIN DIM_MONTH m
    ON d.MONTH_ID = m.MONTH_ID
JOIN DIM_QUARTER q
    ON m.QUARTER_ID = q.QUARTER_ID
JOIN DIM_YEAR y
    ON q.YEAR_ID = y.YEAR_ID
ORDER BY d.DATE_ID;

SELECT
    COUNT(*) AS TOTAL_CUSTOMERS,
    COUNT(CITY_ID) AS CUSTOMERS_WITH_CITY_ID
FROM DIM_CUSTOMER;

ALTER TABLE DIM_CUSTOMER
ADD CONSTRAINT FK_CUSTOMER_CITY
FOREIGN KEY (CITY_ID)
REFERENCES DIM_CITY(CITY_ID);

ALTER TABLE DIM_BRANCH
ADD CONSTRAINT FK_BRANCH_CITY
FOREIGN KEY (CITY_ID)
REFERENCES DIM_CITY(CITY_ID);

ALTER TABLE DIM_PRODUCT
ADD CONSTRAINT FK_PRODUCT_BRAND
FOREIGN KEY (BRAND_ID)
REFERENCES DIM_BRAND(BRAND_ID);

ALTER TABLE DIM_DATE
ADD CONSTRAINT FK_DATE_MONTH
FOREIGN KEY (MONTH_ID)
REFERENCES DIM_MONTH(MONTH_ID);

SELECT
    (SELECT COUNT(*) FROM DIM_CUSTOMER WHERE CITY_ID IS NOT NULL) AS CUSTOMERS_CONNECTED,
    (SELECT COUNT(*) FROM DIM_BRANCH WHERE CITY_ID IS NOT NULL) AS BRANCHES_CONNECTED,
    (SELECT COUNT(*) FROM DIM_PRODUCT WHERE BRAND_ID IS NOT NULL) AS PRODUCTS_CONNECTED,
    (SELECT COUNT(*) FROM DIM_DATE WHERE MONTH_ID IS NOT NULL) AS DATES_CONNECTED;

SHOW IMPORTED KEYS IN ACCOUNT;

SELECT
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    city.CITY_NAME,
    s.STATE_NAME,
    r.REGION_NAME,
    SUM(f.QUANTITY) AS TOTAL_QUANTITY,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES f
JOIN DIM_CUSTOMER c
    ON f.CUSTOMER_ID = c.CUSTOMER_ID
JOIN DIM_CITY city
    ON c.CITY_ID = city.CITY_ID
JOIN DIM_STATE s
    ON city.STATE_ID = s.STATE_ID
JOIN DIM_REGION r
    ON s.REGION_ID = r.REGION_ID
GROUP BY
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    city.CITY_NAME,
    s.STATE_NAME,
    r.REGION_NAME
ORDER BY c.CUSTOMER_ID;

SELECT
    p.PRODUCT_ID,
    p.PRODUCT_NAME,
    b.BRAND_NAME,
    c.CATEGORY_NAME,
    SUM(f.QUANTITY) AS TOTAL_QUANTITY,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES f
JOIN DIM_PRODUCT p
    ON f.PRODUCT_ID = p.PRODUCT_ID
JOIN DIM_BRAND b
    ON p.BRAND_ID = b.BRAND_ID
JOIN DIM_CATEGORY c
    ON b.CATEGORY_ID = c.CATEGORY_ID
GROUP BY
    p.PRODUCT_ID,
    p.PRODUCT_NAME,
    b.BRAND_NAME,
    c.CATEGORY_NAME
ORDER BY p.PRODUCT_ID;

SELECT
    b.BRANCH_ID,
    b.BRANCH_NAME,
    city.CITY_NAME,
    s.STATE_NAME,
    r.REGION_NAME,
    SUM(f.QUANTITY) AS TOTAL_QUANTITY,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES f
JOIN DIM_BRANCH b
    ON f.BRANCH_ID = b.BRANCH_ID
JOIN DIM_CITY city
    ON b.CITY_ID = city.CITY_ID
JOIN DIM_STATE s
    ON city.STATE_ID = s.STATE_ID
JOIN DIM_REGION r
    ON s.REGION_ID = r.REGION_ID
GROUP BY
    b.BRANCH_ID,
    b.BRANCH_NAME,
    city.CITY_NAME,
    s.STATE_NAME,
    r.REGION_NAME
ORDER BY b.BRANCH_ID;

SELECT
    COUNT(*) AS TOTAL_SALES,
    SUM(QUANTITY) AS TOTAL_QUANTITY,
    SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES;

SELECT
    r.REGION_NAME,
    COUNT(DISTINCT f.SALE_ID) AS TOTAL_SALES,
    SUM(f.QUANTITY) AS TOTAL_QUANTITY,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES f
JOIN DIM_BRANCH b
    ON f.BRANCH_ID = b.BRANCH_ID
JOIN DIM_CITY city
    ON b.CITY_ID = city.CITY_ID
JOIN DIM_STATE s
    ON city.STATE_ID = s.STATE_ID
JOIN DIM_REGION r
    ON s.REGION_ID = r.REGION_ID
GROUP BY r.REGION_NAME
ORDER BY r.REGION_NAME;