CREATE OR REPLACE DATABASE RETAIL_SCHEMAS_DW;
CREATE OR REPLACE SCHEMA RETAIL_SCHEMAS_DW.SCHEMA_COMPARISON;

USE DATABASE RETAIL_SCHEMAS_DW;
USE SCHEMA SCHEMA_COMPARISON;

SELECT CURRENT_DATABASE() AS current_database, CURRENT_SCHEMA() AS current_schema;

CREATE OR REPLACE TABLE STAR_DIM_STORE (
    STORE_KEY        NUMBER AUTOINCREMENT PRIMARY KEY,
    STORE_ID         NUMBER,
    STORE_NAME       VARCHAR(100),
    CITY             VARCHAR(50),
    STATE            VARCHAR(50),
    REGION_NAME      VARCHAR(50),
    REGIONAL_MANAGER VARCHAR(100)
);

CREATE OR REPLACE TABLE STAR_DIM_PRODUCT (
    PRODUCT_KEY      NUMBER AUTOINCREMENT PRIMARY KEY,
    PRODUCT_ID       NUMBER,
    PRODUCT_NAME     VARCHAR(100),
    SUBCATEGORY_NAME VARCHAR(50),
    CATEGORY_NAME    VARCHAR(50),
    UNIT_PRICE       NUMBER(10,2)
);

INSERT INTO STAR_DIM_STORE (STORE_ID, STORE_NAME, CITY, STATE, REGION_NAME, REGIONAL_MANAGER)
VALUES
    (201, 'Metro Flagship',  'Hyderabad',   'Telangana',      'South', 'Rajesh Kumar'),
    (202, 'Express Hub',     'Warangal',    'Telangana',      'South', 'Rajesh Kumar'),
    (203, 'Coastal Center',  'Vijayawada',  'Andhra Pradesh', 'South', 'Rajesh Kumar'),
    (204, 'Western Mart',    'Nagpur',      'Maharashtra',    'West',  'Sunil Verma');

INSERT INTO STAR_DIM_PRODUCT (PRODUCT_ID, PRODUCT_NAME, SUBCATEGORY_NAME, CATEGORY_NAME, UNIT_PRICE)
VALUES
    (501, 'Laptop Pro',       'Laptops',     'Electronics', 75000.00),
    (502, 'Wireless Mouse',   'Accessories', 'Electronics',  1500.00),
    (503, 'Ergonomic Chair',  'Office',      'Furniture',   12000.00),
    (504, 'Coffee Maker',     'Kitchen',     'Appliances',   4500.00);

CREATE OR REPLACE TABLE STAR_FACT_SALES (
    SALES_KEY        NUMBER AUTOINCREMENT PRIMARY KEY,
    TRANSACTION_ID   VARCHAR(50),
    TRANSACTION_DATE DATE,
    CUSTOMER_ID      NUMBER,
    STORE_KEY        NUMBER REFERENCES STAR_DIM_STORE(STORE_KEY),
    PRODUCT_KEY      NUMBER REFERENCES STAR_DIM_PRODUCT(PRODUCT_KEY),
    QUANTITY         NUMBER,
    TOTAL_AMOUNT     NUMBER(12,2)
);

INSERT INTO STAR_FACT_SALES
    (TRANSACTION_ID, TRANSACTION_DATE, CUSTOMER_ID, STORE_KEY, PRODUCT_KEY, QUANTITY, TOTAL_AMOUNT)
SELECT
    t.transaction_id,
    t.transaction_date,
    t.customer_id,
    s.STORE_KEY,
    p.PRODUCT_KEY,
    t.quantity,
    t.quantity * t.unit_price AS total_amount
FROM (
    SELECT 'TXN-3001' AS transaction_id, '2026-05-01'::DATE AS transaction_date, 101 AS customer_id, 201 AS store_id, 501 AS product_id, 1 AS quantity, 75000.00 AS unit_price
    UNION ALL SELECT 'TXN-3002', '2026-05-02'::DATE, 102, 202, 502, 2, 1500.00
    UNION ALL SELECT 'TXN-3003', '2026-05-03'::DATE, 103, 203, 503, 1, 12000.00
    UNION ALL SELECT 'TXN-3004', '2026-05-04'::DATE, 104, 201, 504, 1, 4500.00
    UNION ALL SELECT 'TXN-3005', '2026-05-05'::DATE, 105, 204, 502, 3, 1500.00
) t
JOIN STAR_DIM_STORE   s ON s.STORE_ID   = t.store_id
JOIN STAR_DIM_PRODUCT p ON p.PRODUCT_ID = t.product_id;

CREATE OR REPLACE TABLE SNOW_DIM_REGION (
    REGION_KEY       NUMBER AUTOINCREMENT PRIMARY KEY,
    REGION_NAME      VARCHAR(50),
    REGIONAL_MANAGER VARCHAR(100)
);

CREATE OR REPLACE TABLE SNOW_DIM_STORE (
    STORE_KEY   NUMBER AUTOINCREMENT PRIMARY KEY,
    STORE_ID    NUMBER,
    STORE_NAME  VARCHAR(100),
    CITY        VARCHAR(50),
    STATE       VARCHAR(50),
    REGION_KEY  NUMBER REFERENCES SNOW_DIM_REGION(REGION_KEY)
);

CREATE OR REPLACE TABLE SNOW_DIM_CATEGORY (
    CATEGORY_KEY  NUMBER AUTOINCREMENT PRIMARY KEY,
    CATEGORY_NAME VARCHAR(50)
);

CREATE OR REPLACE TABLE SNOW_DIM_SUBCATEGORY (
    SUBCATEGORY_KEY  NUMBER AUTOINCREMENT PRIMARY KEY,
    SUBCATEGORY_NAME VARCHAR(50),
    CATEGORY_KEY     NUMBER REFERENCES SNOW_DIM_CATEGORY(CATEGORY_KEY)
);

CREATE OR REPLACE TABLE SNOW_DIM_PRODUCT (
    PRODUCT_KEY      NUMBER AUTOINCREMENT PRIMARY KEY,
    PRODUCT_ID       NUMBER,
    PRODUCT_NAME     VARCHAR(100),
    UNIT_PRICE       NUMBER(10,2),
    SUBCATEGORY_KEY  NUMBER REFERENCES SNOW_DIM_SUBCATEGORY(SUBCATEGORY_KEY)
);

INSERT INTO SNOW_DIM_REGION (REGION_NAME, REGIONAL_MANAGER)
VALUES
    ('South', 'Rajesh Kumar'),
    ('West',  'Sunil Verma');

INSERT INTO SNOW_DIM_STORE (STORE_ID, STORE_NAME, CITY, STATE, REGION_KEY)
SELECT st.store_id, st.store_name, st.city, st.state, r.REGION_KEY
FROM (
    SELECT 201 AS store_id, 'Metro Flagship' AS store_name, 'Hyderabad'  AS city, 'Telangana'      AS state, 'South' AS region_name
    UNION ALL SELECT 202, 'Express Hub',    'Warangal',   'Telangana',      'South'
    UNION ALL SELECT 203, 'Coastal Center', 'Vijayawada', 'Andhra Pradesh', 'South'
    UNION ALL SELECT 204, 'Western Mart',   'Nagpur',     'Maharashtra',    'West'
) st
JOIN SNOW_DIM_REGION r ON r.REGION_NAME = st.region_name;

INSERT INTO SNOW_DIM_CATEGORY (CATEGORY_NAME)
VALUES ('Electronics'), ('Furniture'), ('Appliances');

INSERT INTO SNOW_DIM_SUBCATEGORY (SUBCATEGORY_NAME, CATEGORY_KEY)
SELECT sub.subcategory_name, c.CATEGORY_KEY
FROM (
    SELECT 'Laptops' AS subcategory_name, 'Electronics' AS category_name
    UNION ALL SELECT 'Accessories', 'Electronics'
    UNION ALL SELECT 'Office',      'Furniture'
    UNION ALL SELECT 'Kitchen',     'Appliances'
) sub
JOIN SNOW_DIM_CATEGORY c ON c.CATEGORY_NAME = sub.category_name;

INSERT INTO SNOW_DIM_PRODUCT (PRODUCT_ID, PRODUCT_NAME, UNIT_PRICE, SUBCATEGORY_KEY)
SELECT p.product_id, p.product_name, p.unit_price, sc.SUBCATEGORY_KEY
FROM (
    SELECT 501 AS product_id, 'Laptop Pro'      AS product_name, 'Laptops'     AS subcategory_name, 75000.00 AS unit_price
    UNION ALL SELECT 502, 'Wireless Mouse',  'Accessories', 1500.00
    UNION ALL SELECT 503, 'Ergonomic Chair', 'Office',      12000.00
    UNION ALL SELECT 504, 'Coffee Maker',    'Kitchen',     4500.00
) p
JOIN SNOW_DIM_SUBCATEGORY sc ON sc.SUBCATEGORY_NAME = p.subcategory_name;

CREATE OR REPLACE TABLE SNOW_FACT_SALES (
    SALES_KEY        NUMBER AUTOINCREMENT PRIMARY KEY,
    TRANSACTION_ID   VARCHAR(50),
    TRANSACTION_DATE DATE,
    CUSTOMER_ID      NUMBER,
    STORE_KEY        NUMBER REFERENCES SNOW_DIM_STORE(STORE_KEY),
    PRODUCT_KEY      NUMBER REFERENCES SNOW_DIM_PRODUCT(PRODUCT_KEY),
    QUANTITY         NUMBER,
    TOTAL_AMOUNT     NUMBER(12,2)
);

INSERT INTO SNOW_FACT_SALES
    (TRANSACTION_ID, TRANSACTION_DATE, CUSTOMER_ID, STORE_KEY, PRODUCT_KEY, QUANTITY, TOTAL_AMOUNT)
SELECT
    t.transaction_id,
    t.transaction_date,
    t.customer_id,
    s.STORE_KEY,
    p.PRODUCT_KEY,
    t.quantity,
    t.quantity * t.unit_price AS total_amount
FROM (
    SELECT 'TXN-3001' AS transaction_id, '2026-05-01'::DATE AS transaction_date, 101 AS customer_id, 201 AS store_id, 501 AS product_id, 1 AS quantity, 75000.00 AS unit_price
    UNION ALL SELECT 'TXN-3002', '2026-05-02'::DATE, 102, 202, 502, 2, 1500.00
    UNION ALL SELECT 'TXN-3003', '2026-05-03'::DATE, 103, 203, 503, 1, 12000.00
    UNION ALL SELECT 'TXN-3004', '2026-05-04'::DATE, 104, 201, 504, 1, 4500.00
    UNION ALL SELECT 'TXN-3005', '2026-05-05'::DATE, 105, 204, 502, 3, 1500.00
) t
JOIN SNOW_DIM_STORE   s ON s.STORE_ID   = t.store_id
JOIN SNOW_DIM_PRODUCT p ON p.PRODUCT_ID = t.product_id;

SELECT
    sd.REGION_NAME,
    pd.CATEGORY_NAME,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM STAR_FACT_SALES f
JOIN STAR_DIM_STORE   sd ON f.STORE_KEY   = sd.STORE_KEY
JOIN STAR_DIM_PRODUCT pd ON f.PRODUCT_KEY = pd.PRODUCT_KEY
GROUP BY sd.REGION_NAME, pd.CATEGORY_NAME
ORDER BY sd.REGION_NAME, pd.CATEGORY_NAME;

SELECT
    r.REGION_NAME,
    c.CATEGORY_NAME,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM SNOW_FACT_SALES f
JOIN SNOW_DIM_STORE       s  ON f.STORE_KEY       = s.STORE_KEY
JOIN SNOW_DIM_REGION      r  ON s.REGION_KEY      = r.REGION_KEY
JOIN SNOW_DIM_PRODUCT     p  ON f.PRODUCT_KEY     = p.PRODUCT_KEY
JOIN SNOW_DIM_SUBCATEGORY sc ON p.SUBCATEGORY_KEY = sc.SUBCATEGORY_KEY
JOIN SNOW_DIM_CATEGORY    c  ON sc.CATEGORY_KEY   = c.CATEGORY_KEY
GROUP BY r.REGION_NAME, c.CATEGORY_NAME
ORDER BY r.REGION_NAME, c.CATEGORY_NAME;

SELECT 'Dimension Normalization Level' AS "METRIC / FEATURE", 'Denormalized (Flat)'     AS "STAR SCHEMA", 'Normalized (Hierarchical)' AS "SNOWFLAKE SCHEMA"
UNION ALL SELECT 'Total Dimension Tables',        '2 Tables',                '5 Tables'
UNION ALL SELECT 'Joins for Category Revenue',    '2 Joins (Fact + 2 Dims)', '4 Joins (Fact + 4 Dims)'
UNION ALL SELECT 'Data Redundancy',                'Higher (Repeated text)',  'Lower (Normalized IDs)'
UNION ALL SELECT 'Query Simplicity',                'High (Simple GROUP BY)', 'Lower (Requires nested FKs)';

SELECT
    sd.REGIONAL_MANAGER,
    SUM(f.QUANTITY)     AS TOTAL_ITEMS_SOLD,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_SALES_AMOUNT
FROM STAR_FACT_SALES f
JOIN STAR_DIM_STORE sd ON f.STORE_KEY = sd.STORE_KEY
GROUP BY sd.REGIONAL_MANAGER
ORDER BY TOTAL_SALES_AMOUNT DESC;

SELECT 'Star Schema' AS SCHEMA_TYPE, 'STAR_DIM_STORE' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT FROM STAR_DIM_STORE
UNION ALL SELECT 'Star Schema',      'STAR_DIM_PRODUCT',      COUNT(*) FROM STAR_DIM_PRODUCT
UNION ALL SELECT 'Star Schema',      'STAR_FACT_SALES',       COUNT(*) FROM STAR_FACT_SALES
UNION ALL SELECT 'Snowflake Schema', 'SNOW_DIM_REGION',       COUNT(*) FROM SNOW_DIM_REGION
UNION ALL SELECT 'Snowflake Schema', 'SNOW_DIM_STORE',        COUNT(*) FROM SNOW_DIM_STORE
UNION ALL SELECT 'Snowflake Schema', 'SNOW_DIM_CATEGORY',     COUNT(*) FROM SNOW_DIM_CATEGORY
UNION ALL SELECT 'Snowflake Schema', 'SNOW_DIM_SUBCATEGORY',  COUNT(*) FROM SNOW_DIM_SUBCATEGORY
UNION ALL SELECT 'Snowflake Schema', 'SNOW_DIM_PRODUCT',      COUNT(*) FROM SNOW_DIM_PRODUCT
UNION ALL SELECT 'Snowflake Schema', 'SNOW_FACT_SALES',       COUNT(*) FROM SNOW_FACT_SALES;