CREATE DATABASE IF NOT EXISTS CUSTOMER_HISTORY_DB;
CREATE SCHEMA IF NOT EXISTS CUSTOMER_HISTORY_DB.CUSTOMER_SCHEMA;
USE DATABASE CUSTOMER_HISTORY_DB;
USE SCHEMA CUSTOMER_SCHEMA;

SELECT CURRENT_DATABASE() AS DATABASE_NAME, CURRENT_SCHEMA() AS SCHEMA_NAME;

CREATE OR REPLACE TABLE DIM_CUSTOMER_TYPE1 (
    CUSTOMER_KEY NUMBER AUTOINCREMENT,
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30)
);
DESC TABLE DIM_CUSTOMER_TYPE1;

LIST @CUSTOMER_STAGE;
LIST @CUSTOMER_SCD_DB.CUSTOMER_SCHEMA.CUSTOMER_STAGE;

COPY INTO DIM_CUSTOMER_TYPE1
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
)
FROM @CUSTOMER_SCD_DB.CUSTOMER_SCHEMA.CUSTOMER_STAGE
FILES = ('customers_initial.csv')
FILE_FORMAT = CUSTOMER_SCD_DB.CUSTOMER_SCHEMA.CUSTOMER_CSV_FORMAT;
SELECT COUNT(*) AS RECORD_COUNT
FROM DIM_CUSTOMER_TYPE1;

CREATE OR REPLACE TABLE CUSTOMER_UPDATES (
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30),
    EFFECTIVE_DATE DATE
);

INSERT INTO CUSTOMER_UPDATES
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE
)
VALUES
(101, 'Amit Sharma', 'Bengaluru', 'Karnataka', 'Gold', 'Premium', '2026-04-01'),
(103, 'Rahul Verma', 'Chennai', 'Tamil Nadu', 'Gold', 'Premium', '2026-04-05'),
(104, 'Neha Patel', 'Hyderabad', 'Telangana', 'Platinum', 'Premium', '2026-04-10');

SELECT *
FROM CUSTOMER_UPDATES
ORDER BY CUSTOMER_ID;

UPDATE DIM_CUSTOMER_TYPE1 d
SET
    CUSTOMER_NAME = u.CUSTOMER_NAME,
    CITY = u.CITY,
    STATE = u.STATE,
    MEMBERSHIP = u.MEMBERSHIP,
    SEGMENT = u.SEGMENT
FROM CUSTOMER_UPDATES u
WHERE d.CUSTOMER_ID = u.CUSTOMER_ID;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
FROM DIM_CUSTOMER_TYPE1
ORDER BY CUSTOMER_ID;

SELECT
    CUSTOMER_ID,
    CITY,
    STATE,
    MEMBERSHIP
FROM DIM_CUSTOMER_TYPE1
WHERE CUSTOMER_ID = 101;

CREATE OR REPLACE TABLE DIM_CUSTOMER_TYPE2 (
    CUSTOMER_KEY NUMBER AUTOINCREMENT,
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30),
    EFFECTIVE_DATE DATE,
    EXPIRY_DATE DATE,
    IS_CURRENT BOOLEAN
);

DESC TABLE DIM_CUSTOMER_TYPE2;

INSERT INTO DIM_CUSTOMER_TYPE2
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    '2026-01-01'::DATE,
    '9999-12-31'::DATE,
    TRUE
FROM DIM_CUSTOMER_TYPE1;

SELECT
    COUNT(*) AS TOTAL_RECORDS,
    COUNT_IF(IS_CURRENT = TRUE) AS CURRENT_RECORDS
FROM DIM_CUSTOMER_TYPE2;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_TYPE2
ORDER BY CUSTOMER_ID;

TRUNCATE TABLE DIM_CUSTOMER_TYPE2;

CREATE OR REPLACE TEMPORARY TABLE CUSTOMER_INITIAL_STAGE (
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30)
);

COPY INTO CUSTOMER_INITIAL_STAGE
FROM @CUSTOMER_SCD_DB.CUSTOMER_SCHEMA.CUSTOMER_STAGE
FILES = ('customers_initial.csv')
FILE_FORMAT = CUSTOMER_SCD_DB.CUSTOMER_SCHEMA.CUSTOMER_CSV_FORMAT;

INSERT INTO DIM_CUSTOMER_TYPE2
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    '2026-01-01'::DATE,
    '9999-12-31'::DATE,
    TRUE
FROM CUSTOMER_INITIAL_STAGE;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_TYPE2
ORDER BY CUSTOMER_ID;

UPDATE DIM_CUSTOMER_TYPE2
SET
    EXPIRY_DATE = CASE CUSTOMER_ID
        WHEN 101 THEN '2026-03-31'::DATE
        WHEN 103 THEN '2026-04-04'::DATE
        WHEN 104 THEN '2026-04-09'::DATE
    END,
    IS_CURRENT = FALSE
WHERE CUSTOMER_ID IN (101, 103, 104)
  AND IS_CURRENT = TRUE;

INSERT INTO DIM_CUSTOMER_TYPE2
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
VALUES
(
    101,
    'Amit Sharma',
    'Bengaluru',
    'Karnataka',
    'Gold',
    'Premium',
    '2026-04-01',
    '9999-12-31',
    TRUE
),
(
    103,
    'Rahul Verma',
    'Chennai',
    'Tamil Nadu',
    'Gold',
    'Premium',
    '2026-04-05',
    '9999-12-31',
    TRUE
),
(
    104,
    'Neha Patel',
    'Hyderabad',
    'Telangana',
    'Platinum',
    'Premium',
    '2026-04-10',
    '9999-12-31',
    TRUE
);

SELECT
    CUSTOMER_ID,
    CITY,
    STATE,
    MEMBERSHIP,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_TYPE2
WHERE CUSTOMER_ID IN (101, 103, 104)
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_TYPE2
WHERE CUSTOMER_ID = 103
ORDER BY EFFECTIVE_DATE;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_TYPE2
WHERE CUSTOMER_ID = 104
ORDER BY EFFECTIVE_DATE;

SELECT
    CUSTOMER_KEY,
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_TYPE2
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE;

IS_CURRENT = TRUE
SELECT
    CUSTOMER_KEY,
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_TYPE2
WHERE IS_CURRENT = TRUE
ORDER BY CUSTOMER_ID;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    MEMBERSHIP,
    CITY,
    EFFECTIVE_DATE,
    EXPIRY_DATE
FROM DIM_CUSTOMER_TYPE2
WHERE CUSTOMER_ID = 101
  AND '2026-03-15'::DATE BETWEEN EFFECTIVE_DATE AND EXPIRY_DATE;

SELECT
    'SCD Type 1' AS SCD_TYPE,
    'Old records overwritten' AS HISTORY,
    'No' AS NEW_ROW_FOR_CHANGE,
    'No' AS HISTORICAL_ANALYSIS,
    'No' AS EFFECTIVE_EXPIRY_DATES,
    'Lower' AS STORAGE
UNION ALL
SELECT
    'SCD Type 2',
    'Old records preserved',
    'Yes',
    'Yes',
    'Yes',
    'Higher';

SELECT
    (SELECT COUNT(*)
     FROM DIM_CUSTOMER_TYPE1) AS SCD_TYPE1_RECORD_COUNT,

    (SELECT COUNT(*)
     FROM DIM_CUSTOMER_TYPE2) AS SCD_TYPE2_RECORD_COUNT,

    (SELECT COUNT(*)
     FROM DIM_CUSTOMER_TYPE2
     WHERE IS_CURRENT = TRUE) AS SCD_TYPE2_CURRENT_RECORD_COUNT,

    (SELECT COUNT(*)
     FROM DIM_CUSTOMER_TYPE2
     WHERE IS_CURRENT = FALSE) AS SCD_TYPE2_HISTORICAL_RECORD_COUNT;