//Phase 1: Snowflake Environment
//Task_1: Create Warehouse 
CREATE WAREHOUSE IF NOT EXISTS ENTERPRISE_WH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
USE WAREHOUSE ENTERPRISE_WH;

//Task_2: Create Database
CREATE DATABASE IF NOT EXISTS ENTERPRISE_DB;
USE DATABASE ENTERPRISE_DB;

//Task_3: Create Schema
CREATE SCHEMA IF NOT EXISTS SALES_SCHEMA;
USE SCHEMA SALES_SCHEMA;

//Task_4: Create CSV File Format
CREATE FILE FORMAT IF NOT EXISTS CSV_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
NULL_IF = ('NULL', 'null', '');

SHOW WAREHOUSES;
SHOW DATABASES;
SHOW SCHEMAS;
SHOW FILE FORMATS;

//Task_5: Create Internal Stage
USE DATABASE ENTERPRISE_DB;
USE SCHEMA SALES_SCHEMA;

CREATE STAGE IF NOT EXISTS SALES_STAGE
FILE_FORMAT = CSV_FORMAT;

SHOW STAGES;
//Phase 2: Data Loading
//Task_6: Upload all CSV files
//Task_7: Create all required
USE DATABASE ENTERPRISE_DB;
USE SCHEMA SALES_SCHEMA;

DESC TABLE CUSTOMERS;
DESC TABLE PRODUCTS;
DESC TABLE BRANCHES;
DESC TABLE SALES;

//Task_8: Load sales_history into sales
SELECT *
FROM SALES
ORDER BY SALE_ID;
SELECT *
FROM SALES_STREAM;
//Task_9: Verify the loaded records
USE DATABASE ENTERPRISE_DB;
USE SCHEMA SALES_SCHEMA;

SELECT * FROM SALES 
ORDER BY SALE_ID;

//PHASE_3: INCREMENTAL LOADING

//Task_10: Create a Stream on SALES
CREATE OR REPLACE STREAM SALES_STREAM
ON TABLE SALES;

//Task_11: Load new_sales.txt
COPY INTO SALES
FROM @ENTERPRISE_STAGE/new_sales.txt
FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT')
ON_ERROR = 'ABORT_STATEMENT';

//Task_12: Display only newly inserted records using the Stream
SELECT
    SALE_ID,
    CUSTOMER_ID,
    PRODUCT_ID,
    BRANCH_ID,
    QUANTITY,
    SALE_DATE,
    TOTAL_AMOUNT,
    METADATA$ACTION,
    METADATA$ISUPDATE
FROM SALES_STREAM
ORDER BY SALE_ID;
//Verify duplicates
SELECT
    SALE_ID,
    COUNT(*) AS CNT
FROM SALES
GROUP BY SALE_ID
HAVING COUNT(*) > 1
ORDER BY SALE_ID;

//Task_13: Merge newly arrived records into the SALES tables

MERGE INTO SALES AS TARGET
USING (
    SELECT
        SALE_ID,
        CUSTOMER_ID,
        PRODUCT_ID,
        BRANCH_ID,
        QUANTITY,
        SALE_DATE,
        TOTAL_AMOUNT
    FROM SALES_STREAM
) AS SOURCE
ON TARGET.SALE_ID = SOURCE.SALE_ID

WHEN MATCHED THEN
    UPDATE SET
        TARGET.CUSTOMER_ID = SOURCE.CUSTOMER_ID,
        TARGET.PRODUCT_ID = SOURCE.PRODUCT_ID,
        TARGET.BRANCH_ID = SOURCE.BRANCH_ID,
        TARGET.QUANTITY = SOURCE.QUANTITY,
        TARGET.SALE_DATE = SOURCE.SALE_DATE,
        TARGET.TOTAL_AMOUNT = SOURCE.TOTAL_AMOUNT

WHEN NOT MATCHED THEN
    INSERT (
        SALE_ID,
        CUSTOMER_ID,
        PRODUCT_ID,
        BRANCH_ID,
        QUANTITY,
        SALE_DATE,
        TOTAL_AMOUNT
    )
    VALUES (
        SOURCE.SALE_ID,
        SOURCE.CUSTOMER_ID,
        SOURCE.PRODUCT_ID,
        SOURCE.BRANCH_ID,
        SOURCE.QUANTITY,
        SOURCE.SALE_DATE,
        SOURCE.TOTAL_AMOUNT
    );

//PHASE_4: Data Validation 
//Task_14: Identity duplicate Sale IDs
SELECT
    SALE_ID,
    COUNT(*) AS RECORD_COUNT
FROM SALES
GROUP BY SALE_ID
HAVING COUNT(*) > 1
ORDER BY SALE_ID;

//Task 15: Identify missing Customer IDs
SELECT 
    SALE_ID,
    CUSTOMER_ID
FROM SALES
WHERE CUSTOMER_ID IS NULL
ORDER BY SALE_ID;

//Task_16: Display invalid Product IDs
SELECT 
    S.SALE_ID,
    S.PRODUCT_ID
FROM SALES AS S
LEFT JOIN PRODUCTS AS P
    ON S.PRODUCT_ID = P.PRODUCT_ID
WHERE P.PRODUCT_ID IS NULL
ORDER BY S.SALE_ID;

//Task_17: Count total newly inserted records

SELECT COUNT(*) AS NEWLY_INSERTED_RECORDS
FROM SALES
WHERE SALE_ID BETWEEN 6 AND 10;
//Phase_5: Time Travel
//Task_18: Delete one sales record

DELETE FROM SALES
WHERE SALE_ID = 10;

//Task 19 — Recover the deleted record using Time Travel

INSERT INTO SALES
SELECT *
FROM SALES
AT (OFFSET => -60)
WHERE SALE_ID = 10;

//Task_20: Verify recovery

SELECT
    SALE_ID,
    CUSTOMER_ID,
    PRODUCT_ID,
    BRANCH_ID,
    QUANTITY,
    SALE_DATE,
    TOTAL_AMOUNT
FROM SALES
WHERE SALE_ID = 10;

//PHASE_6: Zero copy clone
//Task_21: Create a clone named: SALES_TEST

CREATE OR REPLACE TABLE SALES_TEST
CLONE SALES;

//Task_22: Display cloned results
SELECT *
FROM SALES_TEST
ORDER BY SALE_ID;

//Task_23: Insert one new record into the clone
INSERT INTO SALES_TEST (
    SALE_ID,
    CUSTOMER_ID,
    PRODUCT_ID,
    BRANCH_ID,
    QUANTITY,
    SALE_DATE,
    TOTAL_AMOUNT
)
VALUES (
    11,
    1,
    103,
    2,
    1,
    '2026-07-11',
    15000.00
);

//Task 24: .Verify that the original SALES table remains unchanged.
SELECT *
FROM SALES
WHERE SALE_ID = 11;

//PHASE_7: Task Automation 
//Task_25: Create a Task that automatically performs incremental loading every day.

CREATE OR REPLACE TASK DAILY_INCREMENTAL_LOAD
    WAREHOUSE = ENTERPRISE_WH
    SCHEDULE = 'USING CRON 0 0 * * * UTC'
    WHEN SYSTEM$STREAM_HAS_DATA('SALES_STREAM')
AS
    MERGE INTO SALES AS TARGET
    USING (
        SELECT
            SALE_ID,
            CUSTOMER_ID,
            PRODUCT_ID,
            BRANCH_ID,
            QUANTITY,
            SALE_DATE,
            TOTAL_AMOUNT
        FROM SALES_STREAM
    ) AS SOURCE
    ON TARGET.SALE_ID = SOURCE.SALE_ID

    WHEN MATCHED THEN
        UPDATE SET
            TARGET.CUSTOMER_ID = SOURCE.CUSTOMER_ID,
            TARGET.PRODUCT_ID = SOURCE.PRODUCT_ID,
            TARGET.BRANCH_ID = SOURCE.BRANCH_ID,
            TARGET.QUANTITY = SOURCE.QUANTITY,
            TARGET.SALE_DATE = SOURCE.SALE_DATE,
            TARGET.TOTAL_AMOUNT = SOURCE.TOTAL_AMOUNT

    WHEN NOT MATCHED THEN
        INSERT (
            SALE_ID,
            CUSTOMER_ID,
            PRODUCT_ID,
            BRANCH_ID,
            QUANTITY,
            SALE_DATE,
            TOTAL_AMOUNT
        )
        VALUES (
            SOURCE.SALE_ID,
            SOURCE.CUSTOMER_ID,
            SOURCE.PRODUCT_ID,
            SOURCE.BRANCH_ID,
            SOURCE.QUANTITY,
            SOURCE.SALE_DATE,
            SOURCE.TOTAL_AMOUNT
        );

//Task_26: Resume the task 
ALTER TASK DAILY_INCREMENTAL_LOAD RESUME;

//Task_27: Verify Task execution

SELECT
    NAME,
    STATE,
    SCHEDULED_TIME,
    COMPLETED_TIME,
    QUERY_ID,
    ERROR_MESSAGE
FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY())
WHERE NAME = 'DAILY_INCREMENTAL_LOAD'
ORDER BY SCHEDULED_TIME DESC;

//PHASE_8: Business Analytics
//Task 28: Generate Customer Revenue Report
SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM SALES AS S
JOIN CUSTOMERS AS C
    ON S.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME
ORDER BY TOTAL_REVENUE DESC;


COPY INTO BRANCHES
FROM @ENTERPRISE_STAGE/branches.csv
FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT')
ON_ERROR = 'ABORT_STATEMENT';

//Task_29: Generate Branch Revenue Report 

SELECT
    B.BRANCH_ID,
    B.BRANCH_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM SALES AS S
JOIN BRANCHES AS B
    ON S.BRANCH_ID = B.BRANCH_ID
GROUP BY
    B.BRANCH_ID,
    B.BRANCH_NAME
ORDER BY TOTAL_REVENUE DESC;

SELECT COUNT(*) AS BRANCH_COUNT
FROM BRANCHES;

//Task_30: Generate Product Revenue Report
SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM SALES AS S
JOIN PRODUCTS AS P
    ON S.PRODUCT_ID = P.PRODUCT_ID
GROUP BY
    P.PRODUCT_ID,
    P.PRODUCT_NAME
ORDER BY TOTAL_REVENUE DESC;

//Task_31: Generate Monthly Revenue Report
SELECT
    DATE_TRUNC('MONTH', SALE_DATE) AS SALES_MONTH,
    SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM SALES
GROUP BY DATE_TRUNC('MONTH', SALE_DATE)
ORDER BY SALES_MONTH;

//Task_32: Highest Revenue Customer
SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM SALES AS S
JOIN CUSTOMERS AS C
    ON S.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 1;

//Task_33: Highest Revenue Branch
SELECT
    B.BRANCH_ID,
    B.BRANCH_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM SALES AS S
JOIN BRANCHES AS B
    ON S.BRANCH_ID = B.BRANCH_ID
GROUP BY
    B.BRANCH_ID,
    B.BRANCH_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 1;

//Task_34: Top 5 Products
SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM SALES AS S
JOIN PRODUCTS AS P
    ON S.PRODUCT_ID = P.PRODUCT_ID
GROUP BY
    P.PRODUCT_ID,
    P.PRODUCT_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 5;

//Task_35: Customer Purchase Frequency
SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    COUNT(S.SALE_ID) AS PURCHASE_FREQUENCY
FROM SALES AS S
JOIN CUSTOMERS AS C
    ON S.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME
ORDER BY PURCHASE_FREQUENCY DESC;

//Task_36: Running Revenue
SELECT
    SALE_DATE,
    SALE_ID,
    TOTAL_AMOUNT,
    SUM(TOTAL_AMOUNT) OVER (
        ORDER BY SALE_DATE, SALE_ID
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS RUNNING_REVENUE
FROM SALES
ORDER BY SALE_DATE, SALE_ID;

//Task_37: Customer Ranking
SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE,
    RANK() OVER (
        ORDER BY SUM(S.TOTAL_AMOUNT) DESC
    ) AS CUSTOMER_RANK
FROM SALES AS S
JOIN CUSTOMERS AS C
    ON S.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME
ORDER BY CUSTOMER_RANK;

//Task_38: Create View: CUSTOMER_REVENUE
CREATE OR REPLACE VIEW CUSTOMER_REVENUE AS
SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM SALES AS S
JOIN CUSTOMERS AS C
    ON S.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME;

//Task_39: Create Materialized View: BRANCH_REVENUE
CREATE OR REPLACE MATERIALIZED VIEW BRANCH_REVENUE AS
SELECT
    BRANCH_ID,
    SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM SALES
GROUP BY BRANCH_ID;

//Task_40: Display data from both Views
SELECT *
FROM CUSTOMER_REVENUE
ORDER BY TOTAL_REVENUE DESC;

SELECT *
FROM BRANCH_REVENUE
ORDER BY TOTAL_REVENUE DESC;