CREATE DATABASE IF NOT EXISTS RETAIL_DW;
CREATE SCHEMA IF NOT EXISTS RETAIL_DW.SALES_ANALYTICS;
USE DATABASE RETAIL_DW;
USE SCHEMA SALES_ANALYTICS;

CREATE OR REPLACE TABLE DIM_STORE (
    STORE_KEY      NUMBER AUTOINCREMENT PRIMARY KEY,
    STORE_ID       NUMBER,
    STORE_NAME     VARCHAR(100),
    CITY           VARCHAR(50),
    STATE          VARCHAR(50),
    STORE_MANAGER  VARCHAR(100)
);

CREATE OR REPLACE TABLE DIM_PRODUCT (
    PRODUCT_KEY   NUMBER AUTOINCREMENT PRIMARY KEY,
    PRODUCT_ID    NUMBER,
    PRODUCT_NAME  VARCHAR(100),
    CATEGORY      VARCHAR(50),
    UNIT_PRICE    NUMBER(10,2)
);

CREATE OR REPLACE TABLE DIM_CUSTOMER_HYBRID (
    CUSTOMER_KEY           NUMBER AUTOINCREMENT PRIMARY KEY,
    CUSTOMER_ID            NUMBER,
    CUSTOMER_NAME          VARCHAR(100),
    CITY                   VARCHAR(50),
    PREVIOUS_CITY          VARCHAR(50),
    STATE                  VARCHAR(50),
    CURRENT_MEMBERSHIP     VARCHAR(30),
    PREVIOUS_MEMBERSHIP    VARCHAR(30),
    HISTORICAL_MEMBERSHIP  VARCHAR(30),
    SEGMENT                VARCHAR(30),
    EFFECTIVE_DATE         DATE,
    EXPIRY_DATE            DATE,
    IS_CURRENT             BOOLEAN
);

INSERT INTO DIM_STORE (STORE_ID, STORE_NAME, CITY, STATE, STORE_MANAGER)
VALUES
    (201, 'Metro Flagship',  'Hyderabad',  'Telangana',      'Rajesh Kumar'),
    (202, 'Express Hub',     'Warangal',   'Telangana',      'Sita Sharma'),
    (203, 'Coastal Center',  'Vijayawada', 'Andhra Pradesh', 'Vikram Rao');

INSERT INTO DIM_PRODUCT (PRODUCT_ID, PRODUCT_NAME, CATEGORY, UNIT_PRICE)
VALUES
    (501, 'Laptop Pro',      'Electronics', 75000.00),
    (502, 'Wireless Mouse',  'Electronics', 1500.00),
    (503, 'Ergonomic Chair', 'Furniture',   12000.00),
    (504, 'Coffee Maker',    'Appliances',  4500.00);

INSERT INTO DIM_CUSTOMER_HYBRID
    (CUSTOMER_ID, CUSTOMER_NAME, CITY, PREVIOUS_CITY, STATE,
     CURRENT_MEMBERSHIP, PREVIOUS_MEMBERSHIP, HISTORICAL_MEMBERSHIP,
     SEGMENT, EFFECTIVE_DATE, EXPIRY_DATE, IS_CURRENT)
VALUES
    (101, 'Amit Sharma',  'Hyderabad',  NULL, 'Telangana',      'Silver', NULL, 'Silver', 'Regular', '2026-01-01', '9999-12-31', TRUE),
    (102, 'Priya Reddy',  'Warangal',   NULL, 'Telangana',      'Gold',   NULL, 'Gold',   'Premium', '2026-01-01', '9999-12-31', TRUE),
    (103, 'Rahul Verma',  'Vijayawada', NULL, 'Andhra Pradesh', 'Silver', NULL, 'Silver', 'Regular', '2026-01-01', '9999-12-31', TRUE),
    (104, 'Neha Patel',   'Hyderabad',  NULL, 'Telangana',      'Gold',   NULL, 'Gold',   'Premium', '2026-01-01', '9999-12-31', TRUE),
    (105, 'Arjun Gupta',  'Nagpur',     NULL, 'Maharashtra',    'Bronze', NULL, 'Bronze', 'Regular', '2026-01-01', '9999-12-31', TRUE);

CREATE OR REPLACE TABLE FACT_SALES (
    SALES_KEY         NUMBER AUTOINCREMENT PRIMARY KEY,
    TRANSACTION_ID    VARCHAR(50),
    TRANSACTION_DATE  DATE,
    CUSTOMER_KEY      NUMBER,
    STORE_KEY         NUMBER,
    PRODUCT_KEY       NUMBER,
    QUANTITY          NUMBER,
    UNIT_PRICE        NUMBER(10,2),
    TOTAL_AMOUNT      NUMBER(12,2),
    FOREIGN KEY (CUSTOMER_KEY) REFERENCES DIM_CUSTOMER_HYBRID(CUSTOMER_KEY),
    FOREIGN KEY (STORE_KEY)    REFERENCES DIM_STORE(STORE_KEY),
    FOREIGN KEY (PRODUCT_KEY)  REFERENCES DIM_PRODUCT(PRODUCT_KEY)
);

INSERT INTO FACT_SALES
    (TRANSACTION_ID, TRANSACTION_DATE, CUSTOMER_KEY, STORE_KEY, PRODUCT_KEY,
     QUANTITY, UNIT_PRICE, TOTAL_AMOUNT)
SELECT
    'TXN-1001', '2026-02-15',
    (SELECT CUSTOMER_KEY FROM DIM_CUSTOMER_HYBRID WHERE CUSTOMER_ID = 101 AND IS_CURRENT = TRUE),
    (SELECT STORE_KEY    FROM DIM_STORE           WHERE STORE_ID = 201),
    (SELECT PRODUCT_KEY  FROM DIM_PRODUCT         WHERE PRODUCT_ID = 501),
    1,
    (SELECT UNIT_PRICE   FROM DIM_PRODUCT         WHERE PRODUCT_ID = 501),
    1 * (SELECT UNIT_PRICE FROM DIM_PRODUCT WHERE PRODUCT_ID = 501);

INSERT INTO FACT_SALES
    (TRANSACTION_ID, TRANSACTION_DATE, CUSTOMER_KEY, STORE_KEY, PRODUCT_KEY,
     QUANTITY, UNIT_PRICE, TOTAL_AMOUNT)
SELECT
    'TXN-1002', '2026-03-10',
    (SELECT CUSTOMER_KEY FROM DIM_CUSTOMER_HYBRID WHERE CUSTOMER_ID = 103 AND IS_CURRENT = TRUE),
    (SELECT STORE_KEY    FROM DIM_STORE           WHERE STORE_ID = 203),
    (SELECT PRODUCT_KEY  FROM DIM_PRODUCT         WHERE PRODUCT_ID = 502),
    2,
    (SELECT UNIT_PRICE   FROM DIM_PRODUCT         WHERE PRODUCT_ID = 502),
    2 * (SELECT UNIT_PRICE FROM DIM_PRODUCT WHERE PRODUCT_ID = 502);

UPDATE DIM_STORE
SET STORE_MANAGER = 'Suresh Menon'
WHERE STORE_ID = 201;

UPDATE DIM_CUSTOMER_HYBRID
SET EXPIRY_DATE = '2026-03-31', IS_CURRENT = FALSE
WHERE CUSTOMER_ID = 101 AND IS_CURRENT = TRUE;

UPDATE DIM_CUSTOMER_HYBRID
SET EXPIRY_DATE = '2026-04-04', IS_CURRENT = FALSE
WHERE CUSTOMER_ID = 103 AND IS_CURRENT = TRUE;

UPDATE DIM_CUSTOMER_HYBRID
SET EXPIRY_DATE = '2026-04-09', IS_CURRENT = FALSE
WHERE CUSTOMER_ID = 104 AND IS_CURRENT = TRUE;

INSERT INTO DIM_CUSTOMER_HYBRID
    (CUSTOMER_ID, CUSTOMER_NAME, CITY, PREVIOUS_CITY, STATE,
     CURRENT_MEMBERSHIP, PREVIOUS_MEMBERSHIP, HISTORICAL_MEMBERSHIP,
     SEGMENT, EFFECTIVE_DATE, EXPIRY_DATE, IS_CURRENT)
VALUES
    (101, 'Amit Sharma', 'Bengaluru', 'Hyderabad',  'Karnataka',  'Gold',     'Silver', 'Gold',     'Premium', '2026-04-01', '9999-12-31', TRUE),
    (103, 'Rahul Verma', 'Chennai',   'Vijayawada', 'Tamil Nadu', 'Gold',     'Silver', 'Gold',     'Premium', '2026-04-05', '9999-12-31', TRUE),
    (104, 'Neha Patel',  'Hyderabad', NULL,         'Telangana',  'Platinum', 'Gold',   'Platinum', 'Premium', '2026-04-10', '9999-12-31', TRUE);

UPDATE DIM_CUSTOMER_HYBRID
SET CITY = 'Bengaluru', PREVIOUS_CITY = 'Hyderabad', STATE = 'Karnataka',
    CURRENT_MEMBERSHIP = 'Gold', PREVIOUS_MEMBERSHIP = 'Silver'
WHERE CUSTOMER_ID = 101;

UPDATE DIM_CUSTOMER_HYBRID
SET CITY = 'Chennai', PREVIOUS_CITY = 'Vijayawada', STATE = 'Tamil Nadu',
    CURRENT_MEMBERSHIP = 'Gold', PREVIOUS_MEMBERSHIP = 'Silver'
WHERE CUSTOMER_ID = 103;

UPDATE DIM_CUSTOMER_HYBRID
SET CITY = 'Hyderabad', PREVIOUS_CITY = NULL, STATE = 'Telangana',
    CURRENT_MEMBERSHIP = 'Platinum', PREVIOUS_MEMBERSHIP = 'Gold'
WHERE CUSTOMER_ID = 104;


INSERT INTO FACT_SALES
    (TRANSACTION_ID, TRANSACTION_DATE, CUSTOMER_KEY, STORE_KEY, PRODUCT_KEY,
     QUANTITY, UNIT_PRICE, TOTAL_AMOUNT)
SELECT
    'TXN-2001', '2026-04-15',
    (SELECT CUSTOMER_KEY FROM DIM_CUSTOMER_HYBRID WHERE CUSTOMER_ID = 101 AND IS_CURRENT = TRUE),
    (SELECT STORE_KEY    FROM DIM_STORE           WHERE STORE_ID = 201),
    (SELECT PRODUCT_KEY  FROM DIM_PRODUCT         WHERE PRODUCT_ID = 503),
    1,
    (SELECT UNIT_PRICE   FROM DIM_PRODUCT         WHERE PRODUCT_ID = 503),
    1 * (SELECT UNIT_PRICE FROM DIM_PRODUCT WHERE PRODUCT_ID = 503);

SELECT
    CUSTOMER_ID, CUSTOMER_NAME, CITY, PREVIOUS_CITY,
    CURRENT_MEMBERSHIP, PREVIOUS_MEMBERSHIP, HISTORICAL_MEMBERSHIP,
    SEGMENT, EFFECTIVE_DATE, EXPIRY_DATE, IS_CURRENT
FROM DIM_CUSTOMER_HYBRID
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE;

SELECT
    f.TRANSACTION_ID,
    f.TRANSACTION_DATE,
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    c.CITY                       AS CURRENT_CITY,
    c.HISTORICAL_MEMBERSHIP      AS MEMBERSHIP_AT_PURCHASE,
    c.SEGMENT                    AS SEGMENT_AT_PURCHASE,
    s.STORE_NAME,
    p.PRODUCT_NAME,
    f.TOTAL_AMOUNT
FROM FACT_SALES f
JOIN DIM_CUSTOMER_HYBRID c ON f.CUSTOMER_KEY = c.CUSTOMER_KEY
JOIN DIM_STORE s           ON f.STORE_KEY    = s.STORE_KEY
JOIN DIM_PRODUCT p         ON f.PRODUCT_KEY  = p.PRODUCT_KEY
WHERE c.CUSTOMER_ID = 101
ORDER BY f.TRANSACTION_DATE;

SELECT 'STORE DIMENSION RECORDS' AS METRIC, COUNT(*) AS VALUE FROM DIM_STORE
UNION ALL
SELECT 'PRODUCT DIMENSION RECORDS', COUNT(*) FROM DIM_PRODUCT
UNION ALL
SELECT 'TOTAL CUSTOMER DIMENSION RECORDS', COUNT(*) FROM DIM_CUSTOMER_HYBRID
UNION ALL
SELECT 'CURRENT CUSTOMER RECORDS', COUNT(*) FROM DIM_CUSTOMER_HYBRID WHERE IS_CURRENT = TRUE
UNION ALL
SELECT 'HISTORICAL CUSTOMER RECORDS', COUNT(*) FROM DIM_CUSTOMER_HYBRID WHERE IS_CURRENT = FALSE
UNION ALL
SELECT 'FACT SALES TRANSACTIONS', COUNT(*) FROM FACT_SALES;

