//Task 1: Create Warehouse

CREATE WAREHOUSE IF NOT EXISTS RETAIL_DW_WH
WITH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

SHOW WAREHOUSES LIKE 'RETAIL_DW_WH';

//Task 2: Create Database

CREATE DATABASE IF NOT EXISTS RETAIL_DW_DB;

SHOW DATABASES LIKE 'RETAIL_DW_DB';

//Task 3: Create Schema

CREATE SCHEMA IF NOT EXISTS RETAIL_DW_DB.RETAIL_SCHEMA;

SHOW SCHEMAS IN DATABASE RETAIL_DW_DB;

//Task 4: Set Current Warehouse, Database and Schema

USE WAREHOUSE RETAIL_DW_WH;

USE DATABASE RETAIL_DW_DB;

USE SCHEMA RETAIL_SCHEMA;

SELECT CURRENT_DATABASE(), CURRENT_SCHEMA();

//Phase 2: File Format ans Stage Setup 
//Task 5: Create CSV File Format

CREATE OR REPLACE FILE FORMAT RETAIL_CSV_FORMAT
TYPE = CSV
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
EMPTY_FIELD_AS_NULL = TRUE;

//Task 6: Create Internal Stage
CREATE OR REPLACE STAGE RETAIL_STAGE
FILE_FORMAT = RETAIL_CSV_FORMAT;
SHOW STAGES;

//Task 7: Verify Stage
LIST @RETAIL_STAGE;

//Phase 3: Create Dimension Tables
//Task 8: Create Customer Dimension 
CREATE OR REPLACE TABLE DIM_CUSTOMER
(
    CUSTOMER_ID NUMBER(38,0) PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    MEMBERSHIP VARCHAR(50)
);

//Task 9: Create Product Dimension 
CREATE OR REPLACE TABLE DIM_PRODUCT
(
    PRODUCT_ID NUMBER(38,0) PRIMARY KEY,
    PRODUCT_NAME VARCHAR(100),
    CATEGORY VARCHAR(100),
    BRAND VARCHAR(100),
    PRICE NUMBER(12,2)
);

//Task 10: Create Branch Dimension 
CREATE OR REPLACE TABLE DIM_BRANCH
(
    BRANCH_ID NUMBER(38,0) PRIMARY KEY,
    BRANCH_NAME VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    REGION VARCHAR(50),
    MANAGER_NAME VARCHAR(100)
);

//Task 11: Create Date Dimension 

CREATE OR REPLACE TABLE DIM_DATE
(
    DATE_ID NUMBER(30,0) PRIMARY KEY,
    DATE DATE,
    DAY NUMBER(2,0),
    DAY_NAME VARCHAR(20),
    WEEK_NO NUMBER(2,0),
    MONTH VARCHAR(20),
    QUARTER VARCHAR(10),
    YEAR NUMBER(4,0),
    IS_WEEKEND VARCHAR(5)
);

//Phase 4: Load Dimension Data
//Task 12: Load Customer Data

COPY INTO DIM_CUSTOMER
FROM @RETAIL_STAGE/customers.csv
FILE_FORMAT = (FORMAT_NAME = 'RETAIL_CSV_FORMAT')
ON_ERROR = 'CONTINUE';

SELECT *
FROM DIM_CUSTOMER
ORDER BY CUSTOMER_ID;

//Task 13: Load Product Data

COPY INTO DIM_PRODUCT
FROM @RETAIL_STAGE/products.csv
FILE_FORMAT = (FORMAT_NAME = 'RETAIL_CSV_FORMAT')
ON_ERROR = 'CONTINUE';

SELECT *
FROM DIM_PRODUCT
ORDER BY PRODUCT_ID;

LIST @RETAIL_STAGE;
SHOW STAGES;
SELECT CURRENT_DATABASE(), CURRENT_SCHEMA(), CURRENT_WAREHOUSE();

//Task 14: Load Branch Data

COPY INTO DIM_BRANCH
FROM @RETAIL_STAGE/branches.csv
FILE_FORMAT = (FORMAT_NAME = 'RETAIL_CSV_FORMAT')
ON_ERROR = 'CONTINUE';

SELECT *
FROM DIM_BRANCH
ORDER BY BRANCH_ID;

//Task 15: Load Date Data
CREATE OR REPLACE FILE FORMAT RETAIL_DATE_FORMAT
TYPE = CSV
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
DATE_FORMAT = 'DD-MM-YYYY'
EMPTY_FIELD_AS_NULL = TRUE;

COPY INTO DIM_DATE
FROM @RETAIL_STAGE/calendar.csv
FILE_FORMAT = (FORMAT_NAME = 'RETAIL_DATE_FORMAT')
ON_ERROR = 'CONTINUE';

SELECT *
FROM DIM_DATE
ORDER BY DATE_ID;

//Task 16: Create FACT_SALES
-- Task 16: Create FACT_SALES

CREATE OR REPLACE TABLE FACT_SALES
(
    SALE_ID NUMBER(38,0) PRIMARY KEY,
    CUSTOMER_ID NUMBER(38,0),
    PRODUCT_ID NUMBER(38,0),
    BRANCH_ID NUMBER(38,0),
    DATE_ID NUMBER(30,0),
    QUANTITY NUMBER(38,0),
    TOTAL_AMOUNT NUMBER(12,2),

    CONSTRAINT FK_SALES_CUSTOMER
        FOREIGN KEY (CUSTOMER_ID)
        REFERENCES DIM_CUSTOMER(CUSTOMER_ID),

    CONSTRAINT FK_SALES_PRODUCT
        FOREIGN KEY (PRODUCT_ID)
        REFERENCES DIM_PRODUCT(PRODUCT_ID),

    CONSTRAINT FK_SALES_BRANCH
        FOREIGN KEY (BRANCH_ID)
        REFERENCES DIM_BRANCH(BRANCH_ID),

    CONSTRAINT FK_SALES_DATE
        FOREIGN KEY (DATE_ID)
        REFERENCES DIM_DATE(DATE_ID)
);

DESC TABLE FACT_SALES;

//Task 17: Load Sales data
COPY INTO FACT_SALES
FROM @RETAIL_STAGE/sales.csv
FILE_FORMAT = (FORMAT_NAME = 'RETAIL_CSV_FORMAT')
ON_ERROR = 'CONTINUE';
//Task 18: Verify FACT_SALES Data
SELECT *
FROM FACT_SALES
ORDER BY SALE_ID;
//Task 19: Check total sales  record count
SELECT COUNT(*) AS TOTAL_SALES_RECORDS
FROM FACT_SALES;

//Task 20: Validate Customer Relationships
SELECT COUNT(*) AS INVALID_CUSTOMERS
FROM FACT_SALES F
LEFT JOIN DIM_CUSTOMER C
    ON F.CUSTOMER_ID = C.CUSTOMER_ID
WHERE C.CUSTOMER_ID IS NULL;

//Task 21: Validate Product Relationships
SELECT COUNT(*) AS INVALID_PRODUCTS
FROM FACT_SALES F
LEFT JOIN DIM_PRODUCT P
    ON F.PRODUCT_ID = P.PRODUCT_ID
WHERE P.PRODUCT_ID IS NULL;

//Task 22: Validate Branch Relationships
SELECT COUNT(*) AS INVALID_BRANCHES
FROM FACT_SALES F
LEFT JOIN DIM_BRANCH B
    ON F.BRANCH_ID = B.BRANCH_ID
WHERE B.BRANCH_ID IS NULL;

//Task 23: Validate Date Relationships
SELECT COUNT(*) AS INVALID_DATES
FROM FACT_SALES F
LEFT JOIN DIM_DATE D
    ON F.DATE_ID = D.DATE_ID
WHERE D.DATE_ID IS NULL;

//Task 24: Customer wise sales report 
SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    SUM(F.QUANTITY) AS TOTAL_QUANTITY,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_SALES
FROM FACT_SALES F
JOIN DIM_CUSTOMER C
    ON F.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME
ORDER BY TOTAL_SALES DESC;

//Task 25: Product wise revenue report
SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.CATEGORY,
    SUM(F.QUANTITY) AS TOTAL_QUANTITY,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_PRODUCT P
    ON F.PRODUCT_ID = P.PRODUCT_ID
GROUP BY
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.CATEGORY
ORDER BY TOTAL_REVENUE DESC;

//Task 26: Branch wise sales report 
SELECT
    B.BRANCH_ID,
    B.BRANCH_NAME,
    B.CITY,
    B.STATE,
    SUM(F.QUANTITY) AS TOTAL_QUANTITY,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_SALES
FROM FACT_SALES F
JOIN DIM_BRANCH B
    ON F.BRANCH_ID = B.BRANCH_ID
GROUP BY
    B.BRANCH_ID,
    B.BRANCH_NAME,
    B.CITY,
    B.STATE
ORDER BY TOTAL_SALES DESC;

//Task 27: Monthly Revenue Report
SELECT
    D.YEAR,
    D.MONTH,
    SUM(F.TOTAL_AMOUNT) AS MONTHLY_REVENUE
FROM FACT_SALES F
JOIN DIM_DATE D
    ON F.DATE_ID = D.DATE_ID
GROUP BY
    D.YEAR,
    D.MONTH
ORDER BY
    D.YEAR,
    D.MONTH;

//Task 28: State wise revenue report
SELECT
    B.STATE,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_BRANCH B
    ON F.BRANCH_ID = B.BRANCH_ID
GROUP BY
    B.STATE
ORDER BY TOTAL_REVENUE DESC;

//Task 29:  Category-wise Revenue Report

SELECT
    P.CATEGORY,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_PRODUCT P
    ON F.PRODUCT_ID = P.PRODUCT_ID
GROUP BY
    P.CATEGORY
ORDER BY TOTAL_REVENUE DESC;

//Task 30: Top 10 Customers based on Total Sales
SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_SALES
FROM FACT_SALES F
JOIN DIM_CUSTOMER C
    ON F.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME
ORDER BY TOTAL_SALES DESC
LIMIT 10;

//Task 31: Top 10 Products based on Revenue
SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.CATEGORY,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_PRODUCT P
    ON F.PRODUCT_ID = P.PRODUCT_ID
GROUP BY
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.CATEGORY
ORDER BY TOTAL_REVENUE DESC
LIMIT 10;

//Task 32: Top 10 Performing Branches
SELECT
    B.BRANCH_ID,
    B.BRANCH_NAME,
    B.CITY,
    B.STATE,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_SALES
FROM FACT_SALES F
JOIN DIM_BRANCH B
    ON F.BRANCH_ID = B.BRANCH_ID
GROUP BY
    B.BRANCH_ID,
    B.BRANCH_NAME,
    B.CITY,
    B.STATE
ORDER BY TOTAL_SALES DESC
LIMIT 10;

//Task 33: Sales Trend Analysis

SELECT
    D.DATE,
    SUM(F.TOTAL_AMOUNT) AS DAILY_REVENUE
FROM FACT_SALES F
JOIN DIM_DATE D
    ON F.DATE_ID = D.DATE_ID
GROUP BY
    D.DATE
ORDER BY
    D.DATE;

//Task 34: Quarterly Revenue Analysis

SELECT
    D.YEAR,
    D.QUARTER,
    SUM(F.TOTAL_AMOUNT) AS QUARTERLY_REVENUE
FROM FACT_SALES F
JOIN DIM_DATE D
    ON F.DATE_ID = D.DATE_ID
GROUP BY
    D.YEAR,
    D.QUARTER
ORDER BY
    D.YEAR,
    D.QUARTER;

//Task 35: Regional Sales Analysis

SELECT
    B.REGION,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_SALES
FROM FACT_SALES F
JOIN DIM_BRANCH B
    ON F.BRANCH_ID = B.BRANCH_ID
GROUP BY
    B.REGION
ORDER BY TOTAL_SALES DESC;

//Task 36: Customer Purchase Analysis

SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    C.MEMBERSHIP,
    COUNT(F.SALE_ID) AS NUMBER_OF_PURCHASES,
    SUM(F.QUANTITY) AS TOTAL_ITEMS_PURCHASED,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_SPENT
FROM FACT_SALES F
JOIN DIM_CUSTOMER C
    ON F.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    C.MEMBERSHIP
ORDER BY TOTAL_SPENT DESC;

//Task 37: Product Performance Dashboard

SELECT
    P.PRODUCT_NAME,
    P.CATEGORY,
    P.BRAND,
    SUM(F.QUANTITY) AS UNITS_SOLD,
    SUM(F.TOTAL_AMOUNT) AS REVENUE
FROM FACT_SALES F
JOIN DIM_PRODUCT P
    ON F.PRODUCT_ID = P.PRODUCT_ID
GROUP BY
    P.PRODUCT_NAME,
    P.CATEGORY,
    P.BRAND
ORDER BY REVENUE DESC;

//Task 38: Branch Performance Dashboard

SELECT
    B.BRANCH_NAME,
    B.STATE,
    B.REGION,
    SUM(F.QUANTITY) AS UNITS_SOLD,
    SUM(F.TOTAL_AMOUNT) AS REVENUE,
    COUNT(F.SALE_ID) AS TRANSACTION_COUNT
FROM FACT_SALES F
JOIN DIM_BRANCH B
    ON F.BRANCH_ID = B.BRANCH_ID
GROUP BY
    B.BRANCH_NAME,
    B.STATE,
    B.REGION
ORDER BY REVENUE DESC;

//Task 39: Complete Star Schema Query

SELECT
    F.SALE_ID,

    C.CUSTOMER_NAME,
    C.MEMBERSHIP,

    P.PRODUCT_NAME,
    P.CATEGORY,
    P.BRAND,

    B.BRANCH_NAME,
    B.CITY AS BRANCH_CITY,
    B.STATE AS BRANCH_STATE,
    B.REGION,

    D.DATE,
    D.MONTH,
    D.QUARTER,
    D.YEAR,

    F.QUANTITY,
    F.TOTAL_AMOUNT

FROM FACT_SALES F

JOIN DIM_CUSTOMER C
    ON F.CUSTOMER_ID = C.CUSTOMER_ID

JOIN DIM_PRODUCT P
    ON F.PRODUCT_ID = P.PRODUCT_ID

JOIN DIM_BRANCH B
    ON F.BRANCH_ID = B.BRANCH_ID

JOIN DIM_DATE D
    ON F.DATE_ID = D.DATE_ID

ORDER BY F.SALE_ID;

//Task 40.1:Show all tables 
SHOW TABLES;
//Task 40.2: Verify DIM_CUSTOMER

SELECT COUNT(*) AS CUSTOMER_COUNT
FROM DIM_CUSTOMER;

//Task 40.3: Verify DIM_PRODUCT

SELECT COUNT(*) AS PRODUCT_COUNT
FROM DIM_PRODUCT;

//Task 40.4: Verify DIM_BRANCH

SELECT COUNT(*) AS BRANCH_COUNT
FROM DIM_BRANCH;

//Task 40.5: Verify DIM_DATE

SELECT COUNT(*) AS DATE_COUNT
FROM DIM_DATE;

//Task 40.6: Verify FACT_SALES

SELECT COUNT(*) AS SALES_COUNT
FROM FACT_SALES;