CREATE DATABASE IF NOT EXISTS FINANCIAL_GATEWAY_DW;
CREATE SCHEMA IF NOT EXISTS FINANCIAL_GATEWAY_DW.PAYMENT_ANALYTICS;

USE DATABASE FINANCIAL_GATEWAY_DW;
USE SCHEMA PAYMENT_ANALYTICS;

CREATE OR REPLACE TABLE BRONZE_PAYMENT_PAYLOADS (
    RAW_PAYLOAD VARIANT,
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

INSERT INTO BRONZE_PAYMENT_PAYLOADS (RAW_PAYLOAD)
SELECT PARSE_JSON(COLUMN1)
FROM VALUES
    ('{"txn_id":"TXN-901","txn_time":"2026-07-10T10:00:00Z","merchant_id":301,"merchant_name":"TechZone","card_number":"4111222233334444","amount":50000.00,"fee_pct":2.5,"status":"APPROVED"}'),
    ('{"txn_id":"TXN-902","txn_time":"2026-07-10T10:15:00Z","merchant_id":302,"merchant_name":"StyleHub","card_number":"5500111122223333","amount":12000.00,"fee_pct":3.0,"status":"APPROVED"}'),
    ('{"txn_id":"TXN-903","txn_time":"2026-07-10T11:00:00Z","merchant_id":301,"merchant_name":"TechZone","card_number":"4111222233334444","amount":25000.00,"fee_pct":2.5,"status":"PENDING"}'),
    ('{"txn_id":"TXN-904","txn_time":"2026-07-10T11:30:00Z","merchant_id":303,"merchant_name":"FreshMart","card_number":"4000111122223333","amount":8500.00,"fee_pct":1.8,"status":"APPROVED"}'),
    ('{"txn_id":"TXN-905","txn_time":"2026-07-10T12:00:00Z","merchant_id":302,"merchant_name":"StyleHub","card_number":"5500111122223333","amount":45000.00,"fee_pct":3.0,"status":"DECLINED"}'),
    ('{"txn_id":"TXN-906","txn_time":"2026-07-10T12:30:00Z","merchant_id":301,"merchant_name":"TechZone","card_number":"4111222233334444","amount":150000.00,"fee_pct":2.5,"status":"APPROVED"}'),
    ('{"txn_id":"TXN-907","txn_time":"2026-07-10T13:00:00Z","merchant_id":303,"merchant_name":"FreshMart","card_number":"4000111122223333","amount":3200.00,"fee_pct":1.8,"status":"APPROVED"}'),
    ('{"txn_id":"TXN-908","txn_time":"2026-07-10T13:15:00Z","merchant_id":302,"merchant_name":"StyleHub","card_number":"5500111122223333","amount":67000.00,"fee_pct":3.0,"status":"PENDING"}');

SELECT COUNT(*) AS TOTAL_BRONZE_RECORDS_CT
FROM BRONZE_PAYMENT_PAYLOADS;

CREATE OR REPLACE TABLE SILVER_CLEANED_TRANSACTIONS (
    TXN_ID VARCHAR(50),
    TXN_TIME TIMESTAMP_TZ,
    MERCHANT_ID NUMBER,
    MERCHANT_NAME VARCHAR(100),
    MASKED_CARD VARCHAR(19),
    GROSS_AMOUNT NUMBER(12,2),
    FEE_PCT NUMBER(5,2),
    PROCESSING_FEE NUMBER(12,2),
    NET_SETTLEMENT_AMOUNT NUMBER(12,2),
    STATUS VARCHAR(20)
);

INSERT INTO SILVER_CLEANED_TRANSACTIONS (
    TXN_ID,
    TXN_TIME,
    MERCHANT_ID,
    MERCHANT_NAME,
    MASKED_CARD,
    GROSS_AMOUNT,
    FEE_PCT,
    PROCESSING_FEE,
    NET_SETTLEMENT_AMOUNT,
    STATUS
)

SELECT
    RAW_PAYLOAD:txn_id::VARCHAR,
    RAW_PAYLOAD:txn_time::TIMESTAMP_TZ,
    RAW_PAYLOAD:merchant_id::NUMBER,
    RAW_PAYLOAD:merchant_name::VARCHAR,
    'XXXX-XXXX-XXXX-' || RIGHT(RAW_PAYLOAD:card_number::VARCHAR, 4),
    RAW_PAYLOAD:amount::NUMBER(12,2),
    RAW_PAYLOAD:fee_pct::NUMBER(5,2),
    ROUND(
        RAW_PAYLOAD:amount::NUMBER(12,2)
        * (RAW_PAYLOAD:fee_pct::NUMBER(5,2) / 100),
        2
    ),
    ROUND(
        RAW_PAYLOAD:amount::NUMBER(12,2)
        - (
            RAW_PAYLOAD:amount::NUMBER(12,2)
            * (RAW_PAYLOAD:fee_pct::NUMBER(5,2) / 100)
        ),
        2
    ),
    RAW_PAYLOAD:status::VARCHAR
FROM BRONZE_PAYMENT_PAYLOADS;

SELECT
    TXN_ID,
    MERCHANT_ID,
    MERCHANT_NAME,
    MASKED_CARD,
    GROSS_AMOUNT AS GROSS,
    PROCESSING_FEE,
    NET_SETTLEMENT_AMOUNT,
    STATUS
FROM SILVER_CLEANED_TRANSACTIONS
ORDER BY TXN_ID;

CREATE OR REPLACE TABLE GOLD_MERCHANT_SETTLEMENTS (
    MERCHANT_ID NUMBER,
    MERCHANT_NAME VARCHAR(100),
    TOTAL_APPROVED_GROSS NUMBER(14,2),
    TOTAL_GATEWAY_FEES NUMBER(14,2),
    TOTAL_NET_PAYOUT NUMBER(14,2),
    APPROVED_COUNT NUMBER
);

INSERT INTO GOLD_MERCHANT_SETTLEMENTS (
    MERCHANT_ID,
    MERCHANT_NAME,
    TOTAL_APPROVED_GROSS,
    TOTAL_GATEWAY_FEES,
    TOTAL_NET_PAYOUT,
    APPROVED_COUNT
)
SELECT
    MERCHANT_ID,
    MERCHANT_NAME,
    SUM(GROSS_AMOUNT),
    SUM(PROCESSING_FEE),
    SUM(NET_SETTLEMENT_AMOUNT),
    COUNT(*)
FROM SILVER_CLEANED_TRANSACTIONS
WHERE STATUS = 'APPROVED'
GROUP BY MERCHANT_ID, MERCHANT_NAME;

SELECT
    MERCHANT_ID,
    MERCHANT_NAME,
    TOTAL_APPROVED_GROSS,
    TOTAL_GATEWAY_FEES,
    TOTAL_NET_PAYOUT,
    APPROVED_COUNT
FROM GOLD_MERCHANT_SETTLEMENTS
ORDER BY MERCHANT_ID;

UPDATE SILVER_CLEANED_TRANSACTIONS
SET STATUS = 'REFUNDED'
WHERE MERCHANT_NAME = 'TechZone'
  AND STATUS = 'APPROVED';

SET CORRUPTION_UPDATE_QUERY_ID = LAST_QUERY_ID();

SELECT
    TXN_ID,
    MERCHANT_NAME,
    GROSS_AMOUNT AS GROSS,
    STATUS
FROM SILVER_CLEANED_TRANSACTIONS
BEFORE (STATEMENT => $CORRUPTION_UPDATE_QUERY_ID)
WHERE MERCHANT_NAME = 'TechZone'
  AND STATUS = 'APPROVED'
ORDER BY TXN_ID;

UPDATE SILVER_CLEANED_TRANSACTIONS AS CURRENT_DATA
SET STATUS = HISTORICAL_DATA.STATUS
FROM (
    SELECT
        TXN_ID,
        STATUS
    FROM SILVER_CLEANED_TRANSACTIONS
    BEFORE (STATEMENT => $CORRUPTION_UPDATE_QUERY_ID)
    WHERE MERCHANT_NAME = 'TechZone'
      AND STATUS = 'APPROVED'
) AS HISTORICAL_DATA
WHERE CURRENT_DATA.TXN_ID = HISTORICAL_DATA.TXN_ID
  AND CURRENT_DATA.MERCHANT_NAME = 'TechZone'
  AND CURRENT_DATA.STATUS = 'REFUNDED';

SELECT
    MERCHANT_NAME,
    COUNT_IF(STATUS = 'APPROVED') AS APPROVED_COUNT,
    COUNT_IF(STATUS = 'REFUNDED') AS REFUNDED_COUNT
FROM SILVER_CLEANED_TRANSACTIONS
WHERE MERCHANT_NAME = 'TechZone'
GROUP BY MERCHANT_NAME;

WITH BRONZE_TOTALS AS (
    SELECT COALESCE(SUM(RAW_PAYLOAD:amount::NUMBER(12,2)), 0)::NUMBER(14,2)
        AS BRONZE_GROSS_SUM
    FROM BRONZE_PAYMENT_PAYLOADS
),
SILVER_TOTALS AS (
    SELECT COALESCE(SUM(GROSS_AMOUNT), 0)::NUMBER(14,2)
        AS SILVER_GROSS_SUM
    FROM SILVER_CLEANED_TRANSACTIONS
),
SILVER_APPROVED_TOTALS AS (
    SELECT COALESCE(SUM(GROSS_AMOUNT), 0)::NUMBER(14,2)
        AS SILVER_APPROVED_GROSS_SUM
    FROM SILVER_CLEANED_TRANSACTIONS
    WHERE STATUS = 'APPROVED'
),
GOLD_TOTALS AS (
    SELECT COALESCE(SUM(TOTAL_APPROVED_GROSS), 0)::NUMBER(14,2)
        AS GOLD_GROSS_SUM
    FROM GOLD_MERCHANT_SETTLEMENTS
)
SELECT
    B.BRONZE_GROSS_SUM,
    S.SILVER_GROSS_SUM,
    G.GOLD_GROSS_SUM,
    (
        B.BRONZE_GROSS_SUM = S.SILVER_GROSS_SUM
        AND G.GOLD_GROSS_SUM = A.SILVER_APPROVED_GROSS_SUM
    ) AS DATA_MATCH_FLAG
FROM BRONZE_TOTALS B
CROSS JOIN SILVER_TOTALS S
CROSS JOIN SILVER_APPROVED_TOTALS A
CROSS JOIN GOLD_TOTALS G;

