CREATE DATABASE IF NOT EXISTS PROJECT10_SCD_DB;

CREATE SCHEMA IF NOT EXISTS PROJECT10_SCD_DB.SCD_SCHEMA;

USE DATABASE PROJECT10_SCD_DB;

USE SCHEMA SCD_SCHEMA;

CREATE OR REPLACE TABLE DIM_CUSTOMER_TYPE3
(
    CUSTOMER_KEY INTEGER AUTOINCREMENT,
    CUSTOMER_ID INTEGER,
    CUSTOMER_NAME VARCHAR,
    CITY VARCHAR,
    STATE VARCHAR,
    CURRENT_MEMBERSHIP VARCHAR,
    PREVIOUS_MEMBERSHIP VARCHAR,
    SEGMENT VARCHAR
);

DESC TABLE DIM_CUSTOMER_TYPE3;

CREATE OR REPLACE FILE FORMAT CUSTOMER_CSV_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"';

CREATE OR REPLACE STAGE CUSTOMER_STAGE
FILE_FORMAT = CUSTOMER_CSV_FORMAT;

LIST @CUSTOMER_STAGE;

CREATE OR REPLACE TABLE CUSTOMER_SOURCE
(
    CUSTOMER_ID INTEGER,
    CUSTOMER_NAME VARCHAR,
    CITY VARCHAR,
    STATE VARCHAR,
    MEMBERSHIP VARCHAR,
    SEGMENT VARCHAR
);

COPY INTO CUSTOMER_SOURCE
FROM @CUSTOMER_STAGE/customers_initial.csv
FILE_FORMAT = CUSTOMER_CSV_FORMAT
ON_ERROR = 'CONTINUE';

SELECT *
FROM CUSTOMER_SOURCE
ORDER BY CUSTOMER_ID;
SELECT COUNT(*) AS TOTAL_ROWS
FROM CUSTOMER_SOURCE;

INSERT INTO DIM_CUSTOMER_TYPE3
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    SEGMENT
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    NULL,
    SEGMENT
FROM CUSTOMER_SOURCE;

SELECT *
FROM DIM_CUSTOMER_TYPE3
ORDER BY CUSTOMER_ID;

SELECT COUNT(*) AS TOTAL_ROWS
FROM DIM_CUSTOMER_TYPE3;

CREATE OR REPLACE TABLE CUSTOMER_UPDATES
(
    CUSTOMER_ID INTEGER,
    CUSTOMER_NAME VARCHAR,
    CITY VARCHAR,
    STATE VARCHAR,
    MEMBERSHIP VARCHAR,
    SEGMENT VARCHAR,
    UPDATE_DATE DATE
);

INSERT INTO CUSTOMER_UPDATES
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    UPDATE_DATE
)
VALUES
(101, 'Amit Sharma', 'Bengaluru', 'Karnataka', 'Gold', 'Premium', '2026-04-01'),
(103, 'Rahul Verma', 'Chennai', 'Tamil Nadu', 'Gold', 'Premium', '2026-04-05'),
(104, 'Neha Patel', 'Hyderabad', 'Telangana', 'Platinum', 'Premium', '2026-04-10');

SELECT *
FROM CUSTOMER_UPDATES
ORDER BY CUSTOMER_ID;

MERGE INTO DIM_CUSTOMER_TYPE3 AS TARGET
USING CUSTOMER_UPDATES AS SOURCE
ON TARGET.CUSTOMER_ID = SOURCE.CUSTOMER_ID

WHEN MATCHED THEN
UPDATE SET
    TARGET.CUSTOMER_NAME = SOURCE.CUSTOMER_NAME,
    TARGET.CITY = SOURCE.CITY,
    TARGET.STATE = SOURCE.STATE,
    TARGET.PREVIOUS_MEMBERSHIP = TARGET.CURRENT_MEMBERSHIP,
    TARGET.CURRENT_MEMBERSHIP = SOURCE.MEMBERSHIP,
    TARGET.SEGMENT = SOURCE.SEGMENT;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    SEGMENT
FROM DIM_CUSTOMER_TYPE3
ORDER BY CUSTOMER_ID;

SELECT COUNT(*) AS TOTAL_ROWS
FROM DIM_CUSTOMER_TYPE3;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP
FROM DIM_CUSTOMER_TYPE3
ORDER BY CUSTOMER_ID;

CREATE OR REPLACE TABLE CUSTOMER_UPDATES_2
(
    CUSTOMER_ID INTEGER,
    CUSTOMER_NAME VARCHAR,
    CITY VARCHAR,
    STATE VARCHAR,
    MEMBERSHIP VARCHAR,
    SEGMENT VARCHAR,
    UPDATE_DATE DATE
);

INSERT INTO CUSTOMER_UPDATES_2
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    UPDATE_DATE
)
VALUES
(
    101,
    'Amit Sharma',
    'Bengaluru',
    'Karnataka',
    'Platinum',
    'Premium',
    '2026-06-01'
);

SELECT *
FROM CUSTOMER_UPDATES_2;

MERGE INTO DIM_CUSTOMER_TYPE3 AS TARGET
USING CUSTOMER_UPDATES_2 AS SOURCE
ON TARGET.CUSTOMER_ID = SOURCE.CUSTOMER_ID

WHEN MATCHED THEN
UPDATE SET
    TARGET.CUSTOMER_NAME = SOURCE.CUSTOMER_NAME,
    TARGET.CITY = SOURCE.CITY,
    TARGET.STATE = SOURCE.STATE,
    TARGET.PREVIOUS_MEMBERSHIP = TARGET.CURRENT_MEMBERSHIP,
    TARGET.CURRENT_MEMBERSHIP = SOURCE.MEMBERSHIP,
    TARGET.SEGMENT = SOURCE.SEGMENT;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP
FROM DIM_CUSTOMER_TYPE3
WHERE CUSTOMER_ID = 101;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    SEGMENT
FROM DIM_CUSTOMER_TYPE3
ORDER BY CUSTOMER_ID;
SELECT COUNT(*) AS TOTAL_ROWS
FROM DIM_CUSTOMER_TYPE3;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    PREVIOUS_MEMBERSHIP,
    CURRENT_MEMBERSHIP,
    SEGMENT
FROM DIM_CUSTOMER_TYPE3
ORDER BY CUSTOMER_ID;

CREATE OR REPLACE TABLE DIM_CUSTOMER_TYPE6
(
    CUSTOMER_KEY INTEGER AUTOINCREMENT,
    CUSTOMER_ID INTEGER,
    CUSTOMER_NAME VARCHAR,
    CITY VARCHAR,
    STATE VARCHAR,
    CURRENT_MEMBERSHIP VARCHAR,
    PREVIOUS_MEMBERSHIP VARCHAR,
    SEGMENT VARCHAR,
    EFFECTIVE_DATE DATE,
    END_DATE DATE,
    IS_CURRENT BOOLEAN
);

DESC TABLE DIM_CUSTOMER_TYPE6;

INSERT INTO DIM_CUSTOMER_TYPE6
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    END_DATE,
    IS_CURRENT
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    NULL,
    SEGMENT,
    '2026-01-01',
    '9999-12-31',
    TRUE
FROM CUSTOMER_SOURCE;

SELECT *
FROM DIM_CUSTOMER_TYPE6
ORDER BY CUSTOMER_ID;

SELECT COUNT(*) AS TOTAL_ROWS
FROM DIM_CUSTOMER_TYPE6;

CREATE OR REPLACE TABLE CUSTOMER_TYPE6_UPDATES
(
    CUSTOMER_ID INTEGER,
    CUSTOMER_NAME VARCHAR,
    CITY VARCHAR,
    STATE VARCHAR,
    MEMBERSHIP VARCHAR,
    SEGMENT VARCHAR,
    UPDATE_DATE DATE
);

INSERT INTO CUSTOMER_TYPE6_UPDATES
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    UPDATE_DATE
)
VALUES
(101, 'Amit Sharma', 'Bengaluru', 'Karnataka', 'Gold', 'Premium', '2026-04-01'),
(103, 'Rahul Verma', 'Chennai', 'Tamil Nadu', 'Gold', 'Premium', '2026-04-05'),
(104, 'Neha Patel', 'Hyderabad', 'Telangana', 'Platinum', 'Premium', '2026-04-10');

SELECT *
FROM CUSTOMER_TYPE6_UPDATES
ORDER BY CUSTOMER_ID;

UPDATE DIM_CUSTOMER_TYPE6 AS TARGET
SET
    END_DATE = SOURCE.UPDATE_DATE - 1,
    IS_CURRENT = FALSE
FROM CUSTOMER_TYPE6_UPDATES AS SOURCE
WHERE TARGET.CUSTOMER_ID = SOURCE.CUSTOMER_ID
  AND TARGET.IS_CURRENT = TRUE;

SELECT
    CUSTOMER_ID,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    EFFECTIVE_DATE,
    END_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_TYPE6
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE;

INSERT INTO DIM_CUSTOMER_TYPE6
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    END_DATE,
    IS_CURRENT
)
SELECT
    SOURCE.CUSTOMER_ID,
    SOURCE.CUSTOMER_NAME,
    SOURCE.CITY,
    SOURCE.STATE,
    SOURCE.MEMBERSHIP,
    OLD.CURRENT_MEMBERSHIP,
    SOURCE.SEGMENT,
    SOURCE.UPDATE_DATE,
    '9999-12-31',
    TRUE
FROM CUSTOMER_TYPE6_UPDATES AS SOURCE
JOIN DIM_CUSTOMER_TYPE6 AS OLD
    ON SOURCE.CUSTOMER_ID = OLD.CUSTOMER_ID
WHERE OLD.IS_CURRENT = FALSE
  AND OLD.END_DATE = SOURCE.UPDATE_DATE - 1;

SELECT COUNT(*) AS TOTAL_ROWS
FROM DIM_CUSTOMER_TYPE6;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    END_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_TYPE6
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    SEGMENT
FROM DIM_CUSTOMER_TYPE6
WHERE IS_CURRENT = TRUE
ORDER BY CUSTOMER_ID;


SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CURRENT_MEMBERSHIP,
    EFFECTIVE_DATE,
    END_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_TYPE6
WHERE IS_CURRENT = FALSE
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE;

SELECT COUNT(*) AS TOTAL_ROWS
FROM DIM_CUSTOMER_TYPE6;

SELECT COUNT(*) AS CURRENT_ROWS
FROM DIM_CUSTOMER_TYPE6
WHERE IS_CURRENT = TRUE;

SELECT COUNT(*) AS HISTORICAL_ROWS
FROM DIM_CUSTOMER_TYPE6
WHERE IS_CURRENT = FALSE;

SELECT DISTINCT
    CUSTOMER_ID,
    CUSTOMER_NAME
FROM DIM_CUSTOMER_TYPE6
WHERE IS_CURRENT = FALSE
ORDER BY CUSTOMER_ID;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CURRENT_MEMBERSHIP,
    EFFECTIVE_DATE,
    END_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_TYPE6
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP
FROM DIM_CUSTOMER_TYPE6
WHERE IS_CURRENT = TRUE
ORDER BY CUSTOMER_ID;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP
FROM DIM_CUSTOMER_TYPE3
ORDER BY CUSTOMER_ID;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    EFFECTIVE_DATE,
    END_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_TYPE6
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE;