CREATE OR REPLACE DATABASE HEALTHCARE_DW;
CREATE OR REPLACE SCHEMA HEALTHCARE_DW.SCHEMA_COMPARE_LAB;

USE DATABASE HEALTHCARE_DW;
USE SCHEMA SCHEMA_COMPARE_LAB;

SELECT CURRENT_DATABASE() AS current_database, CURRENT_SCHEMA() AS current_schema;


CREATE OR REPLACE TABLE STAR_DIM_HOSPITAL (
    HOSPITAL_KEY     NUMBER AUTOINCREMENT PRIMARY KEY,
    HOSPITAL_ID      NUMBER,
    HOSPITAL_NAME    VARCHAR(100),
    CITY             VARCHAR(50),
    STATE            VARCHAR(50),
    NETWORK_NAME     VARCHAR(100),
    NETWORK_DIRECTOR VARCHAR(100)
);

CREATE OR REPLACE TABLE STAR_DIM_TREATMENT (
    TREATMENT_KEY        NUMBER AUTOINCREMENT PRIMARY KEY,
    TREATMENT_ID         NUMBER,
    TREATMENT_NAME       VARCHAR(100),
    DIAGNOSIS_GROUP_NAME VARCHAR(50),
    STANDARD_COST        NUMBER(12,2)
);

INSERT INTO STAR_DIM_HOSPITAL (HOSPITAL_ID, HOSPITAL_NAME, CITY, STATE, NETWORK_NAME, NETWORK_DIRECTOR)
VALUES
    (1001, 'Apollo Jubilee Hills', 'Hyderabad',  'Telangana', 'Apollo Healthcare Group', 'Dr. Ramesh'),
    (1002, 'Apollo Reach',         'Warangal',   'Telangana', 'Apollo Healthcare Group', 'Dr. Ramesh'),
    (2001, 'Manipal Central',      'Bengaluru',  'Karnataka', 'Manipal Hospitals',       'Dr. Priya');
INSERT INTO STAR_DIM_TREATMENT (TREATMENT_ID, TREATMENT_NAME, DIAGNOSIS_GROUP_NAME, STANDARD_COST)
VALUES
    (501, 'Coronary Angioplasty', 'Cardiology',       150000.00),
    (502, 'Knee Replacement',     'Orthopedics',      220000.00),
    (503, 'Appendectomy',         'General Surgery',   45000.00);

CREATE OR REPLACE TABLE STAR_FACT_CLAIMS (
    CLAIM_KEY        NUMBER AUTOINCREMENT PRIMARY KEY,
    CLAIM_ID         VARCHAR(50),
    CLAIM_DATE       DATE,
    PATIENT_ID       NUMBER,
    HOSPITAL_KEY     NUMBER REFERENCES STAR_DIM_HOSPITAL(HOSPITAL_KEY),
    TREATMENT_KEY    NUMBER REFERENCES STAR_DIM_TREATMENT(TREATMENT_KEY),
    CLAIMED_AMOUNT   NUMBER(12,2),
    APPROVED_AMOUNT  NUMBER(12,2)
); 
INSERT INTO STAR_FACT_CLAIMS
    (CLAIM_ID, CLAIM_DATE, PATIENT_ID, HOSPITAL_KEY, TREATMENT_KEY, CLAIMED_AMOUNT, APPROVED_AMOUNT)
SELECT
    c.claim_id,
    c.claim_date,
    c.patient_id,
    h.HOSPITAL_KEY,
    t.TREATMENT_KEY,
    c.claimed_amount,
    c.approved_amount
FROM (
    SELECT 'CLM-9001' AS claim_id, '2026-06-01'::DATE AS claim_date, 701 AS patient_id, 1001 AS hospital_id, 501 AS treatment_id, 160000.00 AS claimed_amount, 150000.00 AS approved_amount
    UNION ALL SELECT 'CLM-9002', '2026-06-05'::DATE, 702, 1002, 503,  50000.00, 45000.00
    UNION ALL SELECT 'CLM-9003', '2026-06-10'::DATE, 703, 2001, 502, 230000.00, 22000.00
    UNION ALL SELECT 'CLM-9004', '2026-06-12'::DATE, 701, 1001, 503,  48000.00, 45000.00
) c
JOIN STAR_DIM_HOSPITAL  h ON h.HOSPITAL_ID  = c.hospital_id
JOIN STAR_DIM_TREATMENT t ON t.TREATMENT_ID = c.treatment_id;
 
CREATE OR REPLACE TABLE SNOW_DIM_NETWORK (
    NETWORK_KEY      NUMBER AUTOINCREMENT PRIMARY KEY,
    NETWORK_ID       NUMBER,
    NETWORK_NAME     VARCHAR(100),
    NETWORK_DIRECTOR VARCHAR(100)
);

CREATE OR REPLACE TABLE SNOW_DIM_HOSPITAL (
    HOSPITAL_KEY  NUMBER AUTOINCREMENT PRIMARY KEY,
    HOSPITAL_ID   NUMBER,
    HOSPITAL_NAME VARCHAR(100),
    CITY          VARCHAR(50),
    STATE         VARCHAR(50),
    NETWORK_KEY   NUMBER REFERENCES SNOW_DIM_NETWORK(NETWORK_KEY)
);

CREATE OR REPLACE TABLE SNOW_DIM_DIAGNOSIS_GROUP (
    DIAGNOSIS_GROUP_KEY  NUMBER AUTOINCREMENT PRIMARY KEY,
    DIAGNOSIS_GROUP_ID   VARCHAR(20),
    DIAGNOSIS_GROUP_NAME VARCHAR(50)
);

CREATE OR REPLACE TABLE SNOW_DIM_TREATMENT (
    TREATMENT_KEY       NUMBER AUTOINCREMENT PRIMARY KEY,
    TREATMENT_ID        NUMBER,
    TREATMENT_NAME      VARCHAR(100),
    STANDARD_COST       NUMBER(12,2),
    DIAGNOSIS_GROUP_KEY  NUMBER REFERENCES SNOW_DIM_DIAGNOSIS_GROUP(DIAGNOSIS_GROUP_KEY)
);

INSERT INTO SNOW_DIM_NETWORK (NETWORK_ID, NETWORK_NAME, NETWORK_DIRECTOR)
VALUES
    (10, 'Apollo Healthcare Group', 'Dr. Ramesh'),
    (20, 'Manipal Hospitals',       'Dr. Priya');

INSERT INTO SNOW_DIM_HOSPITAL (HOSPITAL_ID, HOSPITAL_NAME, CITY, STATE, NETWORK_KEY)
SELECT h.hospital_id, h.hospital_name, h.city, h.state, n.NETWORK_KEY
FROM (
    SELECT 1001 AS hospital_id, 'Apollo Jubilee Hills' AS hospital_name, 'Hyderabad' AS city, 'Telangana' AS state, 10 AS network_id
    UNION ALL SELECT 1002, 'Apollo Reach',    'Warangal',  'Telangana', 10
    UNION ALL SELECT 2001, 'Manipal Central', 'Bengaluru', 'Karnataka', 20
) h
JOIN SNOW_DIM_NETWORK n ON n.NETWORK_ID = h.network_id;

INSERT INTO SNOW_DIM_DIAGNOSIS_GROUP (DIAGNOSIS_GROUP_ID, DIAGNOSIS_GROUP_NAME)
VALUES
    ('DG-CARD', 'Cardiology'),
    ('DG-ORTH', 'Orthopedics'),
    ('DG-SURG', 'General Surgery');
 
INSERT INTO SNOW_DIM_TREATMENT (TREATMENT_ID, TREATMENT_NAME, STANDARD_COST, DIAGNOSIS_GROUP_KEY)
SELECT t.treatment_id, t.treatment_name, t.standard_cost, dg.DIAGNOSIS_GROUP_KEY
FROM (
    SELECT 501 AS treatment_id, 'Coronary Angioplasty' AS treatment_name, 'DG-CARD' AS diagnosis_group_id, 150000.00 AS standard_cost
    UNION ALL SELECT 502, 'Knee Replacement', 'DG-ORTH', 220000.00
    UNION ALL SELECT 503, 'Appendectomy',     'DG-SURG',  45000.00
) t
JOIN SNOW_DIM_DIAGNOSIS_GROUP dg ON dg.DIAGNOSIS_GROUP_ID = t.diagnosis_group_id;

SELECT * FROM SNOW_DIM_DIAGNOSIS_GROUP;

SELECT * FROM SNOW_DIM_NETWORK;
SELECT * FROM SNOW_DIM_HOSPITAL;
SELECT * FROM SNOW_DIM_DIAGNOSIS_GROUP;
SELECT * FROM SNOW_DIM_TREATMENT;

CREATE OR REPLACE TABLE SNOW_FACT_CLAIMS (
    CLAIM_KEY        NUMBER AUTOINCREMENT PRIMARY KEY,
    CLAIM_ID         VARCHAR(50),
    CLAIM_DATE       DATE,
    PATIENT_ID       NUMBER,
    HOSPITAL_KEY     NUMBER REFERENCES SNOW_DIM_HOSPITAL(HOSPITAL_KEY),
    TREATMENT_KEY    NUMBER REFERENCES SNOW_DIM_TREATMENT(TREATMENT_KEY),
    CLAIMED_AMOUNT   NUMBER(12,2),
    APPROVED_AMOUNT  NUMBER(12,2)
);

INSERT INTO SNOW_FACT_CLAIMS
    (CLAIM_ID, CLAIM_DATE, PATIENT_ID, HOSPITAL_KEY, TREATMENT_KEY, CLAIMED_AMOUNT, APPROVED_AMOUNT)
SELECT
    c.claim_id, c.claim_date, c.patient_id, h.HOSPITAL_KEY, t.TREATMENT_KEY, c.claimed_amount, c.approved_amount
FROM (
    SELECT 'CLM-9001' AS claim_id, '2026-06-01'::DATE AS claim_date, 701 AS patient_id, 1001 AS hospital_id, 501 AS treatment_id, 160000.00 AS claimed_amount, 150000.00 AS approved_amount
    UNION ALL SELECT 'CLM-9002', '2026-06-05'::DATE, 702, 1002, 503,  50000.00, 45000.00
    UNION ALL SELECT 'CLM-9003', '2026-06-10'::DATE, 703, 2001, 502, 230000.00, 22000.00
    UNION ALL SELECT 'CLM-9004', '2026-06-12'::DATE, 701, 1001, 503,  48000.00, 45000.00
) c
JOIN SNOW_DIM_HOSPITAL  h ON h.HOSPITAL_ID  = c.hospital_id
JOIN SNOW_DIM_TREATMENT t ON t.TREATMENT_ID = c.treatment_id;

SELECT
    td.DIAGNOSIS_GROUP_NAME,
    SUM(f.CLAIMED_AMOUNT)  AS TOTAL_CLAIMED_AMOUNT,
    SUM(f.APPROVED_AMOUNT) AS TOTAL_APPROVED_AMOUNT
FROM STAR_FACT_CLAIMS f
JOIN STAR_DIM_TREATMENT td ON f.TREATMENT_KEY = td.TREATMENT_KEY
GROUP BY td.DIAGNOSIS_GROUP_NAME
ORDER BY td.DIAGNOSIS_GROUP_NAME;

UPDATE STAR_FACT_CLAIMS SET APPROVED_AMOUNT = 220000.00 WHERE CLAIM_ID = 'CLM-9003';
UPDATE SNOW_FACT_CLAIMS SET APPROVED_AMOUNT = 220000.00 WHERE CLAIM_ID = 'CLM-9003';

SELECT
    dg.DIAGNOSIS_GROUP_NAME,
    SUM(f.CLAIMED_AMOUNT)  AS TOTAL_CLAIMED_AMOUNT,
    SUM(f.APPROVED_AMOUNT) AS TOTAL_APPROVED_AMOUNT
FROM SNOW_FACT_CLAIMS f
JOIN SNOW_DIM_TREATMENT       t  ON f.TREATMENT_KEY       = t.TREATMENT_KEY
JOIN SNOW_DIM_DIAGNOSIS_GROUP dg ON t.DIAGNOSIS_GROUP_KEY  = dg.DIAGNOSIS_GROUP_KEY
GROUP BY dg.DIAGNOSIS_GROUP_NAME
ORDER BY dg.DIAGNOSIS_GROUP_NAME;

-- Star Schema version
SELECT
    hd.NETWORK_DIRECTOR,
    COUNT(*)                AS TOTAL_CLAIMS_HANDLED,
    SUM(f.APPROVED_AMOUNT)  AS TOTAL_APPROVED_AMOUNT
FROM STAR_FACT_CLAIMS f
JOIN STAR_DIM_HOSPITAL hd ON f.HOSPITAL_KEY = hd.HOSPITAL_KEY
GROUP BY hd.NETWORK_DIRECTOR
ORDER BY TOTAL_APPROVED_AMOUNT DESC;

SELECT
    n.NETWORK_DIRECTOR,
    COUNT(*)                AS TOTAL_CLAIMS_HANDLED,
    SUM(f.APPROVED_AMOUNT)  AS TOTAL_APPROVED_AMOUNT
FROM SNOW_FACT_CLAIMS f
JOIN SNOW_DIM_HOSPITAL h ON f.HOSPITAL_KEY = h.HOSPITAL_KEY
JOIN SNOW_DIM_NETWORK  n ON h.NETWORK_KEY  = n.NETWORK_KEY
GROUP BY n.NETWORK_DIRECTOR
ORDER BY TOTAL_APPROVED_AMOUNT DESC;

SELECT
    n.NETWORK_DIRECTOR,
    COUNT(*)                AS TOTAL_CLAIMS_HANDLED,
    SUM(f.APPROVED_AMOUNT)  AS TOTAL_APPROVED_AMOUNT
FROM SNOW_FACT_CLAIMS f
JOIN SNOW_DIM_HOSPITAL h ON f.HOSPITAL_KEY = h.HOSPITAL_KEY
JOIN SNOW_DIM_NETWORK  n ON h.NETWORK_KEY  = n.NETWORK_KEY
GROUP BY n.NETWORK_DIRECTOR
ORDER BY TOTAL_APPROVED_AMOUNT DESC;

SELECT
    'Star Schema' AS SCHEMA_TYPE,
    'STAR_DIM_HOSPITAL' AS UPDATED_TABLE,
    (SELECT COUNT(*) FROM STAR_DIM_HOSPITAL WHERE NETWORK_NAME = 'Apollo Healthcare Group') AS ROWS_UPDATED,
    'Higher (Multiple rows)' AS MAINTENANCE_EFFORT
UNION ALL
SELECT
    'Snowflake Schema',
    'SNOW_DIM_NETWORK',
    (SELECT COUNT(*) FROM SNOW_DIM_NETWORK WHERE NETWORK_ID = 10),
    'Lower (Single row)';

SELECT 'Star Schema' AS SCHEMA_TYPE, 'STAR_DIM_HOSPITAL' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT FROM STAR_DIM_HOSPITAL
UNION ALL SELECT 'Star Schema',      'STAR_DIM_TREATMENT',       COUNT(*) FROM STAR_DIM_TREATMENT
UNION ALL SELECT 'Star Schema',      'STAR_FACT_CLAIMS',         COUNT(*) FROM STAR_FACT_CLAIMS
UNION ALL SELECT 'Snowflake Schema', 'SNOW_DIM_NETWORK',         COUNT(*) FROM SNOW_DIM_NETWORK
UNION ALL SELECT 'Snowflake Schema', 'SNOW_DIM_HOSPITAL',        COUNT(*) FROM SNOW_DIM_HOSPITAL
UNION ALL SELECT 'Snowflake Schema', 'SNOW_DIM_DIAGNOSIS_GROUP', COUNT(*) FROM SNOW_DIM_DIAGNOSIS_GROUP
UNION ALL SELECT 'Snowflake Schema', 'SNOW_DIM_TREATMENT',       COUNT(*) FROM SNOW_DIM_TREATMENT
UNION ALL SELECT 'Snowflake Schema', 'SNOW_FACT_CLAIMS',         COUNT(*) FROM SNOW_FACT_CLAIMS;